dumbhippo/trunk/server/src/com/dumbhippo/server/applications/ApplicationSystemBean.java
package com.dumbhippo.server.applications;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.imageio.ImageIO;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import org.apache.lucene.document.Document;
import org.apache.lucene.search.Hits;
import org.jboss.annotation.IgnoreDependency;
import org.slf4j.Logger;

import com.dumbhippo.Digest;
import com.dumbhippo.GlobalSetup;
import com.dumbhippo.TypeUtils;
import com.dumbhippo.XmlBuilder;
import com.dumbhippo.dm.ReadWriteSession;
import com.dumbhippo.identity20.Guid;
import com.dumbhippo.persistence.AppinfoUpload;
import com.dumbhippo.persistence.Application;
import com.dumbhippo.persistence.ApplicationCategory;
import com.dumbhippo.persistence.ApplicationIcon;
import com.dumbhippo.persistence.ApplicationUsage;
import com.dumbhippo.persistence.ApplicationUserState;
import com.dumbhippo.persistence.ApplicationWmClass;
import com.dumbhippo.persistence.UnmatchedApplicationUsage;
import com.dumbhippo.persistence.User;
import com.dumbhippo.persistence.ValidationException;
import com.dumbhippo.search.SearchSystem;
import com.dumbhippo.server.Configuration;
import com.dumbhippo.server.HippoProperty;
import com.dumbhippo.server.NotFoundException;
import com.dumbhippo.server.Pageable;
import com.dumbhippo.server.PersonViewer;
import com.dumbhippo.server.XmlMethodErrorCode;
import com.dumbhippo.server.XmlMethodException;
import com.dumbhippo.server.Configuration.PropertyNotFoundException;
import com.dumbhippo.server.dm.DataService;
import com.dumbhippo.server.dm.UserDMO;
import com.dumbhippo.server.views.UserViewpoint;
import com.dumbhippo.server.views.Viewpoint;
import com.dumbhippo.tx.RetryException;
import com.dumbhippo.tx.TxCallable;
import com.dumbhippo.tx.TxRunnable;
import com.dumbhippo.tx.TxUtils;

@Stateless
public class ApplicationSystemBean implements ApplicationSystem {
	
	@SuppressWarnings("unused")
	static private final Logger logger = GlobalSetup.getLogger(ApplicationSystemBean.class);

	@PersistenceContext(unitName = "dumbhippo")
	private EntityManager em; 
	
	@EJB
	private Configuration config;
	
	@EJB
	private PersonViewer personViewer;
	
	@EJB
	@IgnoreDependency
	private SearchSystem searchSystem;
	
	public boolean canEditApplications(Viewpoint viewpoint) {
		if (viewpoint instanceof UserViewpoint)
			return true;
			// return identitySpider.isAdministrator(((UserViewpoint)viewpoint).getViewer());
		else
			return false;
	}
	
	public Application lookupById(String id) throws NotFoundException {	
		Application app = em.find(Application.class, id);
		if (app == null)
			throw new NotFoundException(id);
		return app;
	}		
	
	private Date getDefaultSince() {
		return new Date(System.currentTimeMillis() - 31 * 24 * 60 * 60 * 1000L);
	}
		
	public void addUpload(Guid uploaderId, Guid uploadId, AppinfoFile appinfoFile, String comment) {
		User uploader = em.find(User.class, uploaderId.toString());
		boolean isNew = false;
		
		Application application = em.find(Application.class, appinfoFile.getAppId());
		if (application != null) {
			application.setDeleted(false);
		} else {
			application = new Application(appinfoFile.getAppId());
			isNew = true;
		}
		
		updateApplication(application, appinfoFile);
		if (isNew)
			em.persist(application);
		
		updateApplicationCollections(application, appinfoFile);
		
		AppinfoUpload upload = new AppinfoUpload(uploader, comment);
		upload.setId(uploadId.toString());
		upload.setApplication(application);
		upload.setInitialUpload(isNew);
		
		em.persist(upload);
		
		migrateUnmatchedUsage(application);
	}
	
	public void deleteApplication(UserViewpoint viewpoint, String applicationId, String comment) {
		Application application = em.find(Application.class, applicationId);
		application.setDeleted(true);
		
		// We need to mark the application as deleted instead of actually removing
		// it to retain referential integrity for AppinfoUpload, but we can delete
		// the wmClasses and icons for the application. (We *must* delete the
		// wmClasses to avoid problems with the unique constraints on that table.)
		deleteWmClasses(application);
		deleteIcons(application);
		
		AppinfoUpload upload = new AppinfoUpload(viewpoint.getViewer(), comment);
		upload.setApplication(application);
		upload.setDeleteApplication(true);
		
		em.persist(upload);
	}

	private File getAppinfoLocation(Guid uploadId) {
		final File appinfoDir;
		
		try {
			appinfoDir = new File(config.getPropertyNoDefault(HippoProperty.APPINFO_DIR));
		} catch (PropertyNotFoundException e) {
			throw new RuntimeException("appinfoDir property was not set in super configuration");
		}

		return new File(appinfoDir, uploadId + ".dappinfo");
	}
	
	private AppinfoFile getAppinfoFileInternal(AppinfoUpload upload) throws IOException, ValidationException {
		return new AppinfoFile(getAppinfoLocation(upload.getGuid()));
	}
	
	public AppinfoUpload getCurrentUpload(String applicationId) throws NotFoundException {
		Query q = em.createQuery("SELECT au from AppinfoUpload au " +
                " WHERE au.application.id = :applicationId " +
                " ORDER BY uploadDate DESC")
        .setParameter("applicationId", applicationId)
		.setMaxResults(1);

		try {
			return (AppinfoUpload)q.getSingleResult();
		} catch (NoResultException e) {
			throw new NotFoundException("Application not found");
		}
	}

	public AppinfoUploadView getCurrentUploadView(Viewpoint viewpoint, String applicationId) throws NotFoundException {
		AppinfoUpload upload = getCurrentUpload(applicationId);
		return new AppinfoUploadView(upload, personViewer.getPersonView(viewpoint, upload.getUploader()), true);
	}

	public AppinfoFile getAppinfoFile(Guid uploadId) throws NotFoundException {
		AppinfoUpload upload = em.find(AppinfoUpload.class, uploadId.toString());
		
		if (upload.isDeleteApplication()) {
			throw new NotFoundException("Application was deleted");
		}
		
		try {
			return getAppinfoFileInternal(upload);
		} catch (IOException e) {
			throw new RuntimeException("IO Error reading previously uploaded appinfo file", e);
		} catch (ValidationException e) {
			throw new RuntimeException("Validation error reading previously uploaded appinfo file", e);
		}
	}
	
	public AppinfoUploadView getAppinfoUploadView(Viewpoint viewpoint, Guid uploadId) throws NotFoundException {
		AppinfoUpload upload = em.find(AppinfoUpload.class, uploadId.toString());
		if (upload == null)
			throw new NotFoundException("Upload not found");
		
		AppinfoUpload currentUpload = getCurrentUpload(upload.getApplication().getId());
		
		return new AppinfoUploadView(upload, personViewer.getPersonView(viewpoint, upload.getUploader()),
									 upload == currentUpload);
	}
	
	public AppinfoFile getAppinfoFile(AppinfoUpload upload) throws NotFoundException {
		if (upload.isDeleteApplication()) {
			throw new NotFoundException("Application was deleted");
		}
		
		try {
			return getAppinfoFileInternal(upload);
		} catch (IOException e) {
			throw new RuntimeException("IO Error reading previously uploaded appinfo file", e);
		} catch (ValidationException e) {
			throw new RuntimeException("Validation error reading previously uploaded appinfo file", e);
		}
	}

	public void revertApplication(UserViewpoint viewpoint, String applicationId, Guid uploadId, String comment) throws XmlMethodException {
		if (!canEditApplications(viewpoint))
			throw new XmlMethodException(XmlMethodErrorCode.FORBIDDEN, "you don't have permission to edit applications");
		
		AppinfoUpload oldUpload = em.find(AppinfoUpload.class, uploadId.toString());
		if (oldUpload == null)
			throw new XmlMethodException(XmlMethodErrorCode.NOT_FOUND, "uploadId not found");
			
		if (!oldUpload.getApplication().getId().equals(applicationId))
			throw new XmlMethodException(XmlMethodErrorCode.INVALID_ARGUMENT, "uploadId doesn't refer to the right application");
		
		comment = comment.trim();
		if (comment.equals(""))
			throw new XmlMethodException(XmlMethodErrorCode.INVALID_ARGUMENT, "must provide a non-empty comment");
		
		Guid newUploadId = Guid.createNew();
		
		// In principal, we could just reuse the old saved copy we have of the application information.
		// But since the application save location is tied to the ID of the AppinfoUpload object
		// and we want a new AppinfoUpload object (for a new uploader/date/comment), we load
		// in the application data and save it out again.
		
		File saveLocation = getAppinfoLocation(newUploadId);
		AppinfoFile oldFile;
		try {
			oldFile = getAppinfoFileInternal(oldUpload);
		} catch (IOException e) {
			throw new XmlMethodException(XmlMethodErrorCode.FAILED, "IO error reading in old application data");
		} catch (ValidationException e) {
			throw new XmlMethodException(XmlMethodErrorCode.FAILED, "Old application data failed validation: " + e.getMessage());
		}
		
		OutputStream out = null;
		
		try {
			out = new FileOutputStream(saveLocation);
			oldFile.write(out);
			out.close();
			out = null;
		} catch (IOException e) {
			saveLocation.delete();
			throw new XmlMethodException(XmlMethodErrorCode.FAILED, "couldn't resave application data");
		} finally {
			if (out != null) {
				try {
					out.close();
				} catch (IOException e) {
				}
			}
		}

		try {
			addUpload(viewpoint.getViewer().getGuid(), newUploadId, oldFile, comment);
		} catch (RuntimeException e) {

dumbhippo/trunk/server/src/com/dumbhippo/web/UserSigninBean.java
package com.dumbhippo.web;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;
import com.dumbhippo.Site;
import com.dumbhippo.identity20.Guid;
import com.dumbhippo.persistence.Account;
import com.dumbhippo.persistence.User;
import com.dumbhippo.server.Enabled;
import com.dumbhippo.server.IdentitySpider;
import com.dumbhippo.server.NotFoundException;
import com.dumbhippo.server.PersonViewer;
import com.dumbhippo.server.views.PersonView;
import com.dumbhippo.server.views.SystemViewpoint;
import com.dumbhippo.server.views.UserViewpoint;

public class UserSigninBean extends SigninBean {
	@SuppressWarnings("unused")
	private static final Logger logger = GlobalSetup.getLogger(UserSigninBean.class);

	private Boolean musicSharingEnabled; // lazily initialized

	private IdentitySpider spider;
	private PersonViewer viewer;
	private PersonView userView;
	private PersonView userFromSystemView;
	private Guid userGuid;
	private UserViewpoint viewpoint; // lazily initialized
	
	/**
	 * Creates a new SigninBean object for a particular signed in
	 * user. DO NOT CALL THIS CONSTRUCTOR. Use Signin.getForRequest()
	 * instead. 
	 * 
	 * @param user the account object
	 */
	UserSigninBean(Account account, Site site) {
		super(site);
		this.viewpoint = new UserViewpoint(account.getOwner(), site);
		this.userGuid = this.viewpoint.getViewer().getGuid();
	}
	
	private IdentitySpider getSpider() {
		if (spider == null)
			spider = WebEJBUtil.defaultLookup(IdentitySpider.class);
		return spider;
	}
	
	private PersonViewer getViewer() {
		if (viewer == null)
			viewer = WebEJBUtil.defaultLookup(PersonViewer.class);
		return viewer;
	}
		
	public User getUser() {
		return getViewpoint().getViewer();
	}
	
	public PersonView getViewedUser() {
		if (userView == null)
			userView = getViewer().getPersonView(getViewpoint(), getUser());
		return userView;
	}
	
	public PersonView getViewedUserFromSystem() {
		if (userFromSystemView == null)
			userFromSystemView = getViewer().getPersonView(SystemViewpoint.getInstance(), getUser());
		return userFromSystemView;
	}
	
	public String getUserId() {
		return userGuid.toString();
	}
	
	public Guid getUserGuid() {
		return userGuid;
	}
	
	@Override
	public UserViewpoint getViewpoint() {
		if (viewpoint == null) {
			// this happens if there's a resetSessionObjects()
			try {
				User user = getSpider().lookupGuid(User.class, userGuid);
				viewpoint = new UserViewpoint(user, getSite()); 
			} catch (NotFoundException e) {
				throw new RuntimeException("Could not lazily create UserViewpoint object");
			}
		}
		
		return viewpoint;
	}
	
	@Override
	public boolean isValid() {
		return true;
	}
	
	@Override
	public boolean isActive() {
		return getUser().getAccount().isActive() && (getSite() == Site.GNOME || getUser().getAccount().isPublicPage());
	}
	
	@Override
	public void resetSessionObjects() {
		viewpoint = null;
	}	

	@Override
	public boolean getNeedsTermsOfUse() {
		return !getUser().getAccount().getHasAcceptedTerms();
	}
	
	@Override
	public boolean isDisabled() {
		return getUser().getAccount().isDisabled();
	}
	
	public boolean isMusicSharingEnabled() {
		if (musicSharingEnabled == null) {
			IdentitySpider identitySpider = WebEJBUtil.defaultLookup(IdentitySpider.class);
			musicSharingEnabled = Boolean.valueOf(identitySpider.getMusicSharingEnabled(getUser(), Enabled.RAW_PREFERENCE_ONLY));
		}
		return musicSharingEnabled;
	}
}

dumbhippo/trunk/server/web/jsp-gnome/account-types.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>
<%@ taglib tagdir="/WEB-INF/tags/gnome" prefix="gnome" %>

<dh:bean id="accountTypes" class="com.dumbhippo.web.pages.OnlineAccountTypesPage" scope="request"/>

<head>
	<title>Existing Account Types</title>
	<gnome:stylesheet name="site" iefixes="true"/>	
	<gnome:stylesheet name="account-types"/>	
    <dh:script modules="dh.actions"/>	
</head>

<body>
	<gnome:page currentPageLink="account-types">
	    <h3>Existing Account Types</h3>
   		<div class="gnome-learn-more-text">
		    <p>		    
		      Click on the account type to view or edit information about it. You can add new account types <a href="/account-type-add">here</a>.	
		    </p>
        </div> 
        <hr>
        <c:forEach items="${accountTypes.allOnlineAccountTypes.list}" var="accountType">
		    <div><a href="/account-type?type=${accountType.onlineAccountType.name}"><c:out value="${accountType.onlineAccountType.fullName}"/></a></div>
		</c:forEach>
	</gnome:page>
</body>
</html>

dumbhippo/trunk/server/web/jsp-gnome/account.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>
<%@ taglib tagdir="/WEB-INF/tags/gnome" prefix="gnome" %>

<c:if test="${!signin.valid}">
	<%-- this is a bad error message but should never happen since we require signin to get here --%>
	<dht:errorPage>Not signed in</dht:errorPage>
</c:if>

<dht3:requirePersonBean beanClass="com.dumbhippo.web.pages.PersonPage"/>

<dh:bean id="account" class="com.dumbhippo.web.pages.AccountPage" scope="page"/>

<%-- This is a Facebook authetication token and an error message generated by us if we couldn't --%>
<%-- process the token. We use FacebookServlet to process the token, which then redirects here. --%>
<jsp:setProperty name="account" property="facebookAuthToken" param="auth_token"/>
<jsp:setProperty name="account" property="facebookErrorMessage" param="error_message"/>

<dh:script modules="dh.account"/>
<script type="text/javascript">
    dh.account.dhNames = [ <c:forEach items="${account.gnomeSupportedAccounts.list}" var="supportedAccount" varStatus="status"><dh:jsString value="${supportedAccount.onlineAccountType.name}"/> ${status.last ? '];' : ','}</c:forEach>
    dh.account.dhUserInfoTypes = [ <c:forEach items="${account.gnomeSupportedAccounts.list}" var="supportedAccount" varStatus="status"><dh:jsString value="${supportedAccount.userInfoType}"/> ${status.last ? '];' : ','}</c:forEach>
    dh.account.dhValues = [ <c:forEach items="${account.gnomeSupportedAccounts.list}" var="supportedAccount" varStatus="status"><dh:jsString value="${supportedAccount.username}"/> ${status.last ? '];' : ','}</c:forEach>
    dh.account.dhIds = [ <c:forEach items="${account.gnomeSupportedAccounts.list}" var="supportedAccount" varStatus="status"><dh:jsString value="${supportedAccount.id}"/> ${status.last ? '];' : ','}</c:forEach>
    dh.account.dhDomIds = [ <c:forEach items="${account.gnomeSupportedAccounts.list}" var="supportedAccount" varStatus="status"><dh:jsString value="${supportedAccount.domNodeIdName}"/> ${status.last ? '];' : ','}</c:forEach>
</script>

<head>
    <gnome:title><c:out value="${person.viewedPerson.name}"/>'s Account</gnome:title>
	<gnome:stylesheet name="site"/>
	<gnome:stylesheet name="account"/>	
	<gnome:faviconIncludes/>
	<dht3:accountJavascriptSetup account="${account}"/>
	<dh:script module="dh.textinput"/>
</head>
<body>
	<gnome:page currentPageLink="account">
		<dht3:accountStatus enableControl="true" includeDownload="false"/>
		<div id="gnomeAccountContents" class="${signin.active ? 'gnome-account-contents' : 'gnome-account-contents-disabled'}">
			<div style="margin-right: 100px;"><%-- avoid foot logo --%>
				<dht3:accountEditTable account="${account}" termsOfUseNote="${termsOfUseNote}"/>
			</div>
		</div>
	</gnome:page>
	<dht:photoChooser/>
</body>
</html>

dumbhippo/trunk/server/web/jsp-gnome/application.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>
<%@ taglib tagdir="/WEB-INF/tags/gnome" prefix="gnome" %>

<dh:bean id="applications" class="com.dumbhippo.web.pages.ApplicationsPage" scope="request"/>
<dh:bean id="application" class="com.dumbhippo.web.pages.ApplicationPage" scope="page"/>
<jsp:setProperty name="application" property="applicationId" param="id"/>

<c:set var="appView" value="${application.application}"/>

<c:if test="${empty appView || appView.application.deleted}">
	<dht:errorPage>Application not found</dht:errorPage>
</c:if>

<head>
	<title>Application Statistics - <c:out value="${appView.application.name}"/></title>
	<gnome:stylesheet name="site" iefixes="true"/>	
	<gnome:stylesheet name="applications"/>
	<dh:script modules="dh.control,dh.util,dh.event,dh.actions"/>
	<script type="text/javascript">
		dhApplicationId = <dh:jsString value="${appView.application.id}"/>;
		dhApplicationPackageNames = <dh:jsString value="${appView.application.packageNames}"/>;
		dhApplicationDesktopNames = <dh:jsString value="${appView.application.desktopNames}"/>;
		
		function dhApplicationRefresh() {
			var version = dhApplicationApplication.getVersion();
			var run = dhApplicationApplication.getCanRun();
			var install = !run && dhApplicationApplication.getCanInstall();
			if (version != null)
				version = version.replace(/(.*)-.*/, "$1")
			var nolocal = version == null && !run && !install;
			
			document.getElementById("dhApplicationNoLocal").style.display = nolocal ? "block" : "none"; 
			document.getElementById("dhApplicationVersionOuter").style.display = version != null ? "block" : "none"; 
			document.getElementById("dhApplicationRun").style.display = run ? "block" : "none"; 
			document.getElementById("dhApplicationInstall").style.display = install ? "block" : "none"; 
			
			var span = document.getElementById("dhApplicationVersion");
			dh.util.clearNode(span);
			if (version != null)
				span.appendChild(document.createTextNode(version));
		}
		
		function dhApplicationInit() {
			dh.control.createControl();
			dhApplicationApplication = dh.control.control.getOrCreateApplication(dhApplicationId,
																		         dhApplicationPackageNames,
																		         dhApplicationDesktopNames);
	        dhApplicationApplication.onChange = dhApplicationRefresh;
																		
			dhApplicationRefresh();
		}
		
		dh.event.addPageLoadListener(dhApplicationInit);
	</script>	
</head>

<body>
   	<gnome:page currentPageLink="application">
	    <dht3:applicationsTop/>
	    <hr>
	    <table id="dhApplicationsColumns">
	    <tr>
	    <dht3:applicationsLeft currentCategory="${appView.application.category}" linkifyCurrent="true"/>
	    <td id="dhApplicationsMain">
			<div id="dhApplicationsApplications">
	    		<dht3:application application="${appView}" includeStats="false" linkify="false"/>
				
	    		<div class="dh-application-more">
	    			<div class="dh-applications-application-stats-outer">
	    				<div class="dh-applications-application-stats-heading">Rank &amp; Usage</div>
		    			<dht3:applicationStats application="${appView}"/>
	    			</div>
	    			<div id="dhApplicationNoLocal">
	    				<div class="dh-application-no-local-header">No Package Information</div>
	    				<div>
	    					<a href="http://developer.mugshot.org/wiki/Package_Information">Read More</a>
	    				</div>
	    			</div>
	       			<div id="dhApplicationRun" class="dh-application-action" style="display: none;">
	    				<a href="javascript:dhApplicationApplication.run()">Run <c:out value="${appView.application.name}"/></a>
  					</div>
	   				<div id="dhApplicationInstall" class="dh-application-action" style="display: none;">
						<a href="javascript:dhApplicationApplication.install()">Install Now</a>
	    			</div>
		    		<div class="dh-application-more-details">
		    			<div id="dhApplicationVersionOuter" style="display: none;">
	    					Installed version: <span id="dhApplicationVersion"></span>
  						</div>
 					</div>
	    			<div class="dh-grow-div-around-floats"></div>
	    		</div>
	    		<div class="dh-application-description">
	    			${appView.application.descriptionAsHtml}
	    		</div>
	    		<c:if test="${signin.valid}">
					<a href="/application-edit?id=${appView.application.id}">Edit application database entry</a>
	    		</c:if>
    		</div>
	    </td>
	    <td id="dhApplicationsRight">
	    	<%-- FIXME this is too slow right now - change to periodic map/reduce
			<div class="dh-applications-subheading">Popular applications among <c:out value="${appView.application.name}"/> users:</div>
			<dht3:miniApplicationList apps="${application.relatedApplications}"/>
			--%>
	    </td>
	    </tr>
	    </table>
	</gnome:page>
</body>

dumbhippo/trunk/server/web/jsp-gnome/applications-learnmore.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>
<%@ taglib tagdir="/WEB-INF/tags/gnome" prefix="gnome" %>

<head>
	<title>Application Statistics</title>
	<gnome:stylesheet name="site" iefixes="true"/>	
	<gnome:stylesheet name="applications"/>	
	<dh:script module="dh.actions"/>
</head>

<body>
	<gnome:page currentPageLink="applications">
	    <h1>Open Source Application Statistics</h1>
   		<div class="dh-applications-learnmore">
		    <p>
		    	Have you ever looked at a long list of software packages available for
		    	installation and wondered which ones people actually use? GNOME 
		    	developers are working on new ways to find and browse 
		    	applications that take usage statistics into account. You can help out
		    	with the effort by sharing your application usage statistics.
	    	</p>
	    	<p>
				Right now, we're just providing <a href="/applications">global anonymous 
				statistics</a> about the applications that are most frequently used by
				users of the <a href="http://online-desktop.org">GNOME Online Desktop</a>. 
				In the future, we may extend this with other features like
				seeing which applications are most frequently used among your circle of
				friends or finding local people who use a particular application.
	    	</p>
		    <h2>How it works</h2>
		    <p>
			    When application usage statistics are enabled for your account, the 
			    Online Desktop software keeps track of which applications you interact with.
				Periodically it uploads a list of applications that you've used within the
				last day to the server. We don't record anything about what you're doing
				inside the applications, what documents you have open, or even how much
				time you spend inside each application.
			</p>
	    	<c:if test="${signin.valid}">
			    <h2>Your current setting</h2>
			    <div class="dh-applications-settings">
				    Application usage statistics: 
				    <c:choose>
						<c:when test="${signin.user.account.applicationUsageEnabledWithDefault}">
							<input type="radio" name="dhApplicationUsageEnabled" id="dhApplicationUsageOn" checked="true" onclick="dh.actions.setApplicationUsageEnabled(true);"> <label for="dhApplicationUsageOn">On</label>
							<input type="radio" name="dhApplicationUsageEnabled" id="dhApplicationUsageOff" onclick="dh.actions.setApplicationUsageEnabled(false);">	<label for="dhApplicationUsageOff">Off</label>			
						</c:when>
						<c:otherwise>
							<input type="radio" name="dhApplicationUsageEnabled" id="dhApplicationUsageOn" onclick="dh.actions.setApplicationUsageEnabled(true);"> <label for="dhApplicationUsageOn">On</label>
							<input type="radio" name="dhApplicationUsageEnabled" id="dhApplicationUsageOff" checked="true" onclick="dh.actions.setApplicationUsageEnabled(false);">	<label for="dhApplicationUsageOff">Off</label>
						</c:otherwise>
					</c:choose>
			    </div>
		    </c:if>
	    </div>
	</gnome:page>
</body>
</html>