dumbhippo/branches/production/server/src/com/dumbhippo/web/BrowserBean.java
package com.dumbhippo.web;

import java.io.Serializable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;
import com.dumbhippo.server.Configuration;
import com.dumbhippo.server.HippoProperty;
import com.dumbhippo.server.util.EJBUtil;

public class BrowserBean implements Serializable {
	private static final long serialVersionUID = 1L;
	@SuppressWarnings("unused")
	private static final Logger logger = GlobalSetup.getLogger(BrowserBean.class);

	private static final int LOWEST_GECKO_15_VERSION = 20051001;
	private static final int LOWEST_GECKO_10_VERSION = 20041101;
	
	private enum OS { Mac, Windows, Linux, Unknown };
	private enum Browser { Khtml, Gecko, Opera, IE, Unknown };
	public enum Distribution { Fedora, RHEL, Ubuntu, Unknown };
	
	private boolean forceIeAlphaImage = false;
	
	private OS os;
	private Browser browser;
	private boolean isFirefox;
	private Distribution distribution;
	private int browserVersion;
	
	private OS osRequested;
	private Browser browserRequested;
	private Distribution distributionRequested;
	private String osVersion;
	private String osVersionRequested;
	private String architecture;
	private String architectureRequested;
	
	protected BrowserBean(HttpServletRequest request) {
		
		Configuration config = EJBUtil.defaultLookup(Configuration.class);
		forceIeAlphaImage = "true".equals(config.getProperty(HippoProperty.FORCE_IE_ALPHA_IMAGE));
		
		os = OS.Unknown;
		browser = Browser.Unknown;
		isFirefox = false;
		browserVersion = 0;
				
		String userAgent = request.getHeader("User-Agent");
		if (userAgent == null) {
			logger.debug("No User-Agent");
			return;
		}
		
		if (userAgent.contains("X11"))
			os = OS.Linux;
		else if (userAgent.contains("Macintosh"))
			os = OS.Mac;
		else if (userAgent.contains("Windows"))
			os = OS.Windows;

		
		distribution = Distribution.Unknown;
		if (os == OS.Linux) {
			if (userAgent.contains("Fedora")) {
				if (userAgent.contains("fc5")) {
					distribution = Distribution.Fedora;
					osVersion = "5";
				} else if (userAgent.contains("fc6")) {
					distribution = Distribution.Fedora;
					osVersion = "6";
				} else if (userAgent.contains("fc7")) {
					distribution = Distribution.Fedora;
					osVersion = "7";
				}
			} else if (userAgent.contains("Red Hat")) {
				if (userAgent.contains("el4")) {
					distribution = Distribution.RHEL;
					osVersion = "4";
				} else if (userAgent.contains("el5")) {
					distribution = Distribution.RHEL;
					osVersion = "5";
				}
				
			} else if (userAgent.contains("Ubuntu")) {
				if (userAgent.contains("Ubuntu/dapper")) {
					distribution = Distribution.Ubuntu;
					osVersion = "6.05";
				} else if (userAgent.contains("Ubuntu-edgy")) {
					distribution = Distribution.Ubuntu;
					osVersion = "6.10";
				} else if (userAgent.contains("Ubuntu-feisty")) {
					distribution = Distribution.Ubuntu;
					osVersion = "7.04";
				}
			}
		
			// Order is important here - "i686 (x86_64)" is a 32-bit browser on a 64-bit
			// system, in which case we want to offer a 32-bit Mugshot download, so treat
			// as i686.
			
			if (userAgent.contains("i686") || userAgent.contains("i586") || userAgent.contains("i386"))
				architecture = "x86";
			else if (userAgent.contains("x86_64"))
				architecture = "x86_64";
			else if (userAgent.contains("ppc64"))
				architecture = "ppc64";
			else if (userAgent.contains("ppc"))
				architecture = "ppc";
		}
		
		/* note that we aren't counting IE before 5.0 or not on Windows 
		 * as IE ... it's just Unknown.
		 * For Netscape 4 and old Mozilla I'm guessing we should do
		 * the same but would require some research into
		 * gecko/netscape user agent history to see which changes make
		 * sense. 
		 */
		
		if (userAgent.contains("Konqueror") ||
		    userAgent.contains("Safari"))
		    browser = Browser.Khtml;
		else if (userAgent.contains("Gecko")) {
			browser = Browser.Gecko;
			Pattern p = Pattern.compile("Gecko\\/([0-9]+)");
			Matcher m = p.matcher(userAgent);
			if (m.find()) {
				try {
					int geckoVersion = Integer.parseInt(m.group(1));
					if (geckoVersion > LOWEST_GECKO_15_VERSION)
						browserVersion = 15;
					else if (geckoVersion > LOWEST_GECKO_10_VERSION)
						browserVersion = 10;
				} catch (NumberFormatException e) {
				}
			}
			if (userAgent.contains("Firefox")) 
				isFirefox = true;
		} else if (userAgent.contains("Opera")) {
			browser = Browser.Opera;
		} else if (os == OS.Windows && userAgent.contains("MSIE 5.0")) {
			browser = Browser.IE;
		} else if (os == OS.Windows && userAgent.contains("MSIE 5.5")) {
			browser = Browser.IE;
			browserVersion = 55;
		} else if (os == OS.Windows && userAgent.contains("MSIE 6")) {
			browser = Browser.IE;
			browserVersion = 60;
		} else if (os == OS.Windows && 
				(userAgent.contains("MSIE 7") ||
				 userAgent.contains("MSIE 8"))) {
			browser = Browser.IE;
			browserVersion = 70;
		}
		
		String platformOverrideStr = request.getParameter("platform");
		String browserOverrideStr = request.getParameter("browser");
		String distributionOverrideStr = request.getParameter("distribution");

		osRequested = null;
		browserRequested = null;
		distributionRequested = null;
		
		if (platformOverrideStr != null) {
			platformOverrideStr = platformOverrideStr.toLowerCase();
			for (OS o : OS.values()) {
				if (o.name().toLowerCase().equals(platformOverrideStr)) {
					osRequested = o;
					break;
				}
			}
		}

		if (browserOverrideStr != null) {
			browserOverrideStr = browserOverrideStr.toLowerCase();
			for (Browser b : Browser.values()) {
				if (b.name().toLowerCase().equals(browserOverrideStr)) {
					browserRequested = b;
					break;
				}
			}
			/* allow special browser=safari parameter */
			if (browserRequested == null && browserOverrideStr.equals("safari")) {
				osRequested = OS.Mac;
				browserRequested = Browser.Khtml;
			}
		}
		
		if (distributionOverrideStr != null) {
			distributionOverrideStr = distributionOverrideStr.toLowerCase();
			for (Distribution d : Distribution.values()) {
				if (d.name().toLowerCase().equals(distributionOverrideStr)) {
					distributionRequested = d;
					// implies platform=linux
					if (osRequested == null)
						osRequested = OS.Linux;
					break;
				}
			}
		}
		
		osVersionRequested = request.getParameter("osVersion");
		architectureRequested = request.getParameter("architecture");
		
		logger.debug("User agent is '{}' analysis {}", userAgent, this);
	}
	
	public static BrowserBean getForRequest(HttpServletRequest request) {
		BrowserBean bean = (BrowserBean)request.getAttribute("browser");
		if (bean == null) {
			bean = new BrowserBean(request);
			request.setAttribute("browser", bean);
		}
		
		return bean;
	}

	/* 
	 * The "isFooRequested" flavors indicate whether the user explicitly 
	 * chose the given platform/browser, e.g. on /bookmark where you can
	 * look at other browser versions even if you're using a different browser.
	 * 
	 * The plain "isFoo" indicate what user agent someone is using, 
	 * which should be used if you're trying to choose which html/css to 
	 * display or something like that. 
	 */
	
	private boolean isRequested(Browser b) {
		return browserRequested == b || (browserRequested == null && browser == b);
	}
	
	private boolean isRequested(OS o) {
		return osRequested == o || (osRequested == null && os == o);
	}
	
	public boolean isGecko() {
		return browser == Browser.Gecko;
	}

	public boolean isGeckoRequested() {
		return isRequested(Browser.Gecko);
	}
	
	public boolean isGeckoAtLeast10() {
		return isGecko() && browserVersion >= 10;
	}

	public boolean isGeckoAtLeast15() {
		return isGecko() && browserVersion >= 15;
	}
	
	// This method should not be used to determine html content for 
	// anonymous pages for which we use a single cache for all gecko browsers.
	public boolean isFirefox() {
		return isFirefox;
	}

	public boolean isIe() {
		return browser == Browser.IE;
	}

	public boolean isIeRequested() {
		return isRequested(Browser.IE);
	}
	
	public boolean isIeAtLeast55() {
		return isIe() && browserVersion >= 55;
	}

	public boolean isIeAtLeast60() {
		return isIe() && browserVersion >= 60;
	}

	public boolean isKhtml() {
		return browser == Browser.Khtml;
	}

	public boolean isKhtmlRequested() {
		return isRequested(Browser.Khtml);
	}

	public boolean isLinux() {
		return os == OS.Linux;
	}

	public boolean isLinuxRequested() {
		return isRequested(OS.Linux);
	}
	
	public boolean isMac() {
		return os == OS.Mac;
	}

	public boolean isMacRequested() {
		return isRequested(OS.Mac);
	}
	
	public boolean isOpera() {
		return browser == Browser.Opera;
	}

	public boolean isOperaRequested() {
		return isRequested(Browser.Opera);
	}
	
	public boolean isWindows() {
		return os == OS.Windows;
	}
	
	public boolean isWindowsRequested() {
		return isRequested(OS.Windows);
	}

	public boolean isSafari() {
		return isMac() && isKhtml();
	}

	public boolean isSafariRequested() {
		return isMacRequested() && isKhtmlRequested();
	}
	
	public Distribution getDistribution() {
		return distribution; 
	}
	
	public Distribution getDistributionRequested() {
		return distributionRequested != null ? distributionRequested : distribution; 
	}
	
	public String getOsVersion() {
		return osVersion;
	}

	public String getOsVersionRequested() {
		return osVersionRequested != null ? osVersionRequested : osVersion;
	}

	public String getArchitecture() {
		return architecture;
	}
	
	public String getArchitectureRequested() {
		return architectureRequested != null ? architectureRequested : architecture;
	}
	
	public String getSupportedBrowsers() {
		return "Internet Explorer 6 and Firefox 1.5";
	}
	
	public boolean isSupported() {
		return isIeAtLeast60() || isGeckoAtLeast15();
	}
	
	public boolean getIeAlphaImage() {
		return isIeAtLeast55() && (forceIeAlphaImage || browserVersion < 70);
	}
	
	@Override
	public String toString() {

dumbhippo/branches/production/server/src/com/dumbhippo/web/DownloadBean.java
package com.dumbhippo.web;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;
import com.dumbhippo.server.Configuration;
import com.dumbhippo.server.NotFoundException;
import com.dumbhippo.server.downloads.Download;
import com.dumbhippo.server.downloads.DownloadPlatform;

public class DownloadBean extends BrowserBean {
	private static final long serialVersionUID = 1L;
	@SuppressWarnings("unused")
	private static final Logger logger = GlobalSetup.getLogger(DownloadBean.class);
	
	private Configuration configuration;
	private Download download;
	private DownloadPlatform platform;
	
	private DownloadBean(HttpServletRequest request) {
		super(request);
		configuration = WebEJBUtil.defaultLookup(Configuration.class);
		
		String platformString = null;
		String distributionString = null; 
		String osVersion = null;
		String architecture = null;
		
		if (isLinuxRequested()) {
			platformString = "linux";
			if (getDistributionRequested() != null)
				distributionString = getDistributionRequested().toString();
			osVersion = getOsVersionRequested();
			architecture = getArchitectureRequested();
		} else if (isWindowsRequested()) {
			platformString = "windows";
		}

		if (platformString != null) {
			try {
				platform = configuration.getDownloads().findPlatform(platformString);
			} catch (NotFoundException e) {
			}
				
			try {
				download = configuration.getDownloads().findDownload(platformString, distributionString, osVersion, architecture);
			} catch (NotFoundException e) {
			}
		}
	}
	
	public static DownloadBean getForRequest(HttpServletRequest request) {
		DownloadBean bean = (DownloadBean)request.getAttribute("download");
		if (bean == null) {
			bean = new DownloadBean(request);
			request.setAttribute("download", bean);
		}
		
		return bean;
	}
	
	public DownloadPlatform getPlatform() {
		return platform;
	}
	
	public Download getDownload() {
		return download;
	}
}

dumbhippo/branches/production/server/src/com/dumbhippo/web/UserSigninBean.java
package com.dumbhippo.web;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;
import com.dumbhippo.identity20.Guid;
import com.dumbhippo.persistence.Account;
import com.dumbhippo.persistence.User;
import com.dumbhippo.server.Enabled;
import com.dumbhippo.server.IdentitySpider;
import com.dumbhippo.server.NotFoundException;
import com.dumbhippo.server.PersonViewer;
import com.dumbhippo.server.views.PersonView;
import com.dumbhippo.server.views.SystemViewpoint;
import com.dumbhippo.server.views.UserViewpoint;

public class UserSigninBean extends SigninBean {
	@SuppressWarnings("unused")
	private static final Logger logger = GlobalSetup.getLogger(UserSigninBean.class);

	private Boolean musicSharingEnabled; // lazily initialized

	private IdentitySpider spider;
	private PersonViewer viewer;
	private PersonView userView;
	private PersonView userFromSystemView;
	private Guid userGuid;
	private User user; // lazily initialized
	
	/**
	 * Creates a new SigninBean object for a particular signed in
	 * user. DO NOT CALL THIS CONSTRUCTOR. Use Signin.getForRequest()
	 * instead. 
	 * 
	 * @param user the account object
	 */
	UserSigninBean(Account account) {
		this.user = account.getOwner();
		this.userGuid = user.getGuid();
	}
	
	private IdentitySpider getSpider() {
		if (spider == null)
			spider = WebEJBUtil.defaultLookup(IdentitySpider.class);
		return spider;
	}
	
	private PersonViewer getViewer() {
		if (viewer == null)
			viewer = WebEJBUtil.defaultLookup(PersonViewer.class);
		return viewer;
	}
		
	public User getUser() {
		if (user == null) {
			try {
				user = getSpider().lookupGuid(User.class, userGuid);
			} catch (NotFoundException e) {
				throw new RuntimeException("Could not lazily create User object");
			}
		}

		return user;
	}
	
	public PersonView getViewedUser() {
		if (userView == null)
			userView = getViewer().getPersonView(getViewpoint(), getUser());
		return userView;
	}
	
	public PersonView getViewedUserFromSystem() {
		if (userFromSystemView == null)
			userFromSystemView = getViewer().getPersonView(SystemViewpoint.getInstance(), getUser());
		return userFromSystemView;
	}
	
	public String getUserId() {
		return userGuid.toString();
	}
	
	public Guid getUserGuid() {
		return userGuid;
	}
	
	@Override
	public UserViewpoint getViewpoint() {
		return new UserViewpoint(getUser());
	}
	
	@Override
	public boolean isValid() {
		return true;
	}
	
	@Override
	public boolean isActive() {
		return getUser().getAccount().isActive();
	}
	
	@Override
	public void resetSessionObjects() {
		user = null;
	}	

	@Override
	public boolean getNeedsTermsOfUse() {
		return !getUser().getAccount().getHasAcceptedTerms();
	}
	
	@Override
	public boolean isDisabled() {
		return getUser().getAccount().isDisabled();
	}
	
	public boolean isMusicSharingEnabled() {
		if (musicSharingEnabled == null) {
			IdentitySpider identitySpider = WebEJBUtil.defaultLookup(IdentitySpider.class);
			musicSharingEnabled = Boolean.valueOf(identitySpider.getMusicSharingEnabled(getUser(), Enabled.RAW_PREFERENCE_ONLY));
		}
		return musicSharingEnabled;
	}
}

dumbhippo/branches/production/server/web/jsp3/chatwindow.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<dh:bean id="chatwindow" class="com.dumbhippo.web.pages.ChatWindowPage" scope="request"/>
<%-- only one of these params is expected at a time... chatId just means 
	"figure out whether it's post or group" which is less efficient but 
	some calling contexts might not know the type of chat --%>
<jsp:setProperty name="chatwindow" property="postId" param="postId"/>
<jsp:setProperty name="chatwindow" property="groupId" param="groupId"/>
<jsp:setProperty name="chatwindow" property="trackId" param="trackId"/>
<jsp:setProperty name="chatwindow" property="blockId" param="blockId"/>
<jsp:setProperty name="chatwindow" property="chatId" param="chatId"/>

<c:if test="${! chatwindow.aboutSomething}">
	<%-- no post/group/track, or invalid/not-allowed post/group/track --%>
	<dht:errorPage>Can't find this chat</dht:errorPage>
</c:if>

<head>
	<title><c:out value="${chatwindow.title}"/></title>
	<dht3:stylesheet name="site" iefixes="true"/>	
	<dht3:stylesheet name="chatwindow" iefixes="true"/>	
	<dh:script modules="dh.chatwindow,dh.event"/>
	<style type="text/css"> <%-- Vertical sizes are set here so we can do computed heights--%>
		#dhChatHeader {
			top: 0px;
			height: ${chatwindow.headerHeight}px;
		}

		#dhChatMessages {
			top: ${chatwindow.headerHeight}px;
			bottom: 110px;
			height: expression((document.body.clientHeight - ${chatwindow.headerHeight + 110}) + "px");
		}
	</style>
	<script type="text/javascript">
   	    dh.chatwindow.selfId = "${chatwindow.signin.userId}";
        dh.chatwindow.chatId = "${chatwindow.chatId}";
        <c:if test="${!disabled}">
			dh.event.addPageLoadListener(dhChatwindowInit);
		</c:if>
	</script>
</head>

<body scroll="no">
	<div id="dhChatHeader">
		<dht3:block block="${chatwindow.block}" offset="0" blockId="0" showFrom="true" chatHeader="true"/>
	</div>
	<div id="dhChatFooter">
		<div id="dhChatFooterInner">
			<div id="dhChatWhosAround">
				Who's around: <span id="dhChatUserList"></span>
			</div>
			<dht3:chatInput multiline="true" sendlabel="Add" onsend="dh.chatwindow.sendClicked()"/>
		</div>
	</div>
	<div id="dhChatMessages">
		<c:if test="${disabled}">
			<table class="dh-disabled-table">
			<tr>
			<td align="center" valign="center" class="dh-disabled-message">
			    Sorry, we're working to make things better!<br/>
				<a href="http://blog.mugshot.org/?cat=13" target="_blank">Check the blog for updates</a>
			</td>
			</tr>
			</table>
		</c:if>
		<div id="dhChatTooOld" style="display: none">
			<table class="dh-disabled-table">
			<tr>
			<td align="center" valign="center">
				<div class="dh-too-old-message">
					<c:choose>
						<c:when test="${browser.ie}">
						    Your version of the Mugshot software is too old. Please 
						    <a href="http://mugshot.org/download">install the latest version of Mugshot</a> 
						    then try again.
						</c:when>
						<c:otherwise>
							You need to <b>restart Firefox</b> so it uses the latest version of the
							Mugshot browser plugin. Close all Mugshot and Firefox windows,
						    then try reopening the "Quips and Comments" window.  If that
						    doesn't work, you may need to log out and log in again.
						</c:otherwise>
					</c:choose>
				</div>
			</td>
			</tr>
			</table>
		</div>
	</div>
</body>

dumbhippo/branches/production/server/web/jsp3/comingsoon.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:redirect url="/"/>


dumbhippo/branches/production/server/web/jsp3/home.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<%-- this redirects to /person, adds a who parameter if necessary, and preserves existing parameters --%>
<dht3:requireWhoParameter page="/person"/>

dumbhippo/branches/production/server/web/jsp3/links-learnmore.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<dh:bean id="bookmark" class="com.dumbhippo.web.pages.BookmarkPage" scope="request"/>

<head>
	<title>Mugshot Web Swarm - Learn More</title>
	<dht3:stylesheet name="site" iefixes="true"/>	
	<dht3:stylesheet name="download"/>
	<dht:scriptIncludes/>
	<dht:faviconIncludes/>
</head>

<c:choose>
	<c:when test='${browser.geckoRequested}'>
		<c:set var="dragDestImg" value="bookmarkfirefox.gif" scope="page"/>
		<c:set var="browserTitle" value="FIREFOX" scope="page"/>
		<c:set var="unsupported" value="false" scope="page"/>	
	</c:when>
	<c:when test='${browser.safariRequested}'>
		<c:set var="dragDestImg" value="bookmarksafari.gif" scope="page"/>
		<c:set var="browserTitle" value="SAFARI" scope="page"/>
		<c:set var="unsupported" value="false" scope="page"/>	
	</c:when>
</c:choose>

<dht3:page currentPageLink="links-learnmore">
	<dht3:accountStatus includeDownload="false"/>
	<dht3:shinyBox color="grey">
		<div class="dh-download-header-area">
			<div class="dh-download-header">Web Swarm</div>
			<dht3:download page="links-learnmore"/>
		</div>
		<dht3:webSwarmLearnMore>
			<hr height="1px" color="#666666" style="margin: 10px 0px"/>
			<div class="dh-download-section-header">Using <span class="dh-download-product">Web Swarm</span></div>
			<div class="dh-download-section-description">
			<p>
			<c:choose>
				<c:when test="${browser.ieRequested}">
					<div>Since you're using Internet Explorer, you can click the Web Swarm button on your browser's toolbar.</div>
					<img src="/images2/${buildStamp}/toolbarsample.gif"/>
				</c:when>
				<c:when test='${browser.geckoRequested || browser.safariRequested}'>
					<div>Drag the link below onto the Bookmarks toolbar.  Then to share and chat about
						a site with friends, click 'Mugshot Web Swarm' on your Bookmarks toolbar.</div>
					<div id="dhBookmarkHowto">
					<table style="background-color:#ffffff;color:inherit;" cellspacing="10px" cellpadding="0">
					<tr>
					<td width="10px;"><div></div></td>
					<td align="left" valign="bottom"><img src="/images2/${buildStamp}/dragthis.gif"/></td>
					<td align="center" valign="bottom">
					<div id="dhBookmarkLink">
					<a href="javascript:window.open('${bookmark.baseUrl}/sharelink?v=1&amp;url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title)+'&amp;next=close','_NEW','menubar=no,location=no,toolbar=no,scrollbars=yes,status=no,resizable=yes,height=400,width=550,top='+((screen.availHeight-400)/2)+',left='+((screen.availWidth-550)/2));void(0);">Mugshot Web Swarm</a>
					</div>
					</td>
					<td align="right" valign="bottom"><img src="/images2/${dragDestImg}"/></td>
					<td width="10px;"><div></div></td>	
					</tr>
					</table>
					</div>				
				</c:when>
			</c:choose>
			<div>
			Instructions for: <a class="dh-option-list-option" href="?browser=ie">Internet Explorer</a> | 
			<a class="dh-option-list-option" href="?browser=gecko">Firefox</a> | 
			<a class="dh-option-list-option" href="?browser=safari">Safari</a>						
			</div>
			</p>
			<p>To share a web page you're visiting,   In the Web Swarm window,
			enter Mugshot Groups, users or friends' e-mails as recipients.  Write a quick description, and send it off.
			</p>
			<p>A new entry in your stack will appear when you receive Web Swarm shares from friends or Groups.  Click the link in your
			stack to visit the page.  In the Web Swarm bar at the bottom of the shared page, you can see who sent it, who else is there,
			and recent chat comments.  There are also links to forward the page to others, and to save the page as one of your Faves.
			</p>		
			</div>
		</dht3:webSwarmLearnMore>
		<dht3:learnMoreOptions exclude="webSwarm"/>
	</dht3:shinyBox>
</dht3:page>

dumbhippo/branches/production/server/web/jsp3/web-accounts-learnmore.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<head>
	<title>Web Accounts - Learn More</title>
	<dht3:stylesheet name="site" iefixes="true"/>	
	<dht3:stylesheet name="download"/>
	<dht:scriptIncludes/>
	<dht:faviconIncludes/>
</head>

<dht3:page currentPageLink="web-accounts-learnmore">
	<dht3:accountStatus includeDownload="false"/>
	<dht3:shinyBox color="grey">
		<div class="dh-learnmore-section dh-learnmore-section-top">
			<div class="dh-learnmore-header">Web Accounts</div>
			<dht3:download page="web-accounts-learnmore"/>
			<c:if test="${signin.valid}">
			    <span>
			        Add external Web accounts on <i><a href="/account">your account page</a></i>.
			    </span>
			</c:if>   
			We currently support blogs, Facebook, Flickr, and YouTube, with more to come soon.     
		</div>
		<hr size="1" color="#999999" style="margin: 5px 0px">
		<div class="dh-learnmore-section">
			<div class="dh-learnmore-header">Public Accounts</div>
			<div class="dh-learnmore-illustration">
			    <img src="/images3/${buildStamp}/public_accounts_sample.jpg"/></a>
			</div>
			<div class="dh-learnmore-explanation">
			    <p>When you post new blog entries, or upload Flickr photos and YouTube videos, your Mugshot friends 
			    will see those updates on their Mugshot pages and Stackers. You'll also get those updates, to see 
			    how they are displayed to friends. These kinds of updates are visible to anyone, just like on the 
			    sites they come from.</p>
			</div>
			<div class="dh-grow-div-around-floats"></div>		
		</div>		
		<hr size="1" color="#999999" style="margin: 5px 0px">
		<div class="dh-learnmore-section">
			<div class="dh-learnmore-header">Private Accounts</div>
			<div class="dh-learnmore-illustration">
			    <img src="/images3/${buildStamp}/private_accounts_sample.jpg"/></a>			
			</div>
			<div class="dh-learnmore-explanation">
			    <p>Updates from external accounts with private information, like Facebook, will only be visible 
			    to the account owner. Private updates are indicated by a lock icon.</p>          
			    <c:if test="${signin.valid}">
                    <p>Log in to your Facebook account through Mugshot on <i><a href="/account">your account page</a></i> 
                    to receive updates. If you have a Facebook account listed in your Mugshot, you'll get a 
                    Stacker block once a day reminding you to log in. After you log in, a Stacker block will 
                    confirm it.</p>
                </c:if>    
			</div>
			<div class="dh-grow-div-around-floats"></div>			
		</div>		
		<hr size="1" color="#999999" color="#666666" style="margin: 5px 0px">
		<dht3:learnMoreOptions exclude="webAccounts"/>
	</dht3:shinyBox>
</dht3:page>