dumbhippo/branches/production-replaced-2006-12-13/server/src/com/dumbhippo/web/BrowserBean.java
package com.dumbhippo.web;

import java.io.Serializable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;

public class BrowserBean implements Serializable {
	private static final long serialVersionUID = 1L;
	@SuppressWarnings("unused")
	private static final Logger logger = GlobalSetup.getLogger(BrowserBean.class);

	private enum OS { Mac, Windows, Linux, Unknown };
	private enum Browser { Khtml, Gecko, Opera, IE, Unknown };
	private enum Distribution { Fedora5, Fedora6, Unknown };
	
	private OS os;
	private Browser browser;
	private Distribution distribution;
	private int browserVersion;
	
	private OS osRequested;
	private Browser browserRequested;
	private Distribution distributionRequested;
	
	private BrowserBean(HttpServletRequest request) {
		
		os = OS.Unknown;
		browser = Browser.Unknown;
		browserVersion = 0;
				
		String userAgent = request.getHeader("User-Agent");
		if (userAgent == null) {
			logger.debug("No User-Agent");
			return;
		}
		
		if (userAgent.contains("X11"))
			os = OS.Linux;
		else if (userAgent.contains("Macintosh"))
			os = OS.Mac;
		else if (userAgent.contains("Windows"))
			os = OS.Windows;

		distribution = Distribution.Unknown;
		if (userAgent.contains("Fedora")) {
			if (userAgent.contains("fc5"))
				distribution = Distribution.Fedora5;
			else if (userAgent.contains("fc6"))
				distribution = Distribution.Fedora6;
		}
		
		/* note that we aren't counting IE before 5.0 or not on Windows 
		 * as IE ... it's just Unknown.
		 * For Netscape 4 and old Mozilla I'm guessing we should do
		 * the same but would require some research into
		 * gecko/netscape user agent history to see which changes make
		 * sense. 
		 */
		
		if (userAgent.contains("Konqueror") ||
		    userAgent.contains("Safari"))
		    browser = Browser.Khtml;
		else if (userAgent.contains("Gecko")) {
			browser = Browser.Gecko;
			Pattern p = Pattern.compile("Gecko\\/([0-9]+)");
			Matcher m = p.matcher(userAgent);
			if (m.find()) {
				try {
					int geckoVersion = Integer.parseInt(m.group(1));
					if (geckoVersion > 20051001)
						browserVersion = 15;
					else if (geckoVersion > 20041101)
						browserVersion = 10;
				} catch (NumberFormatException e) {
				}
			}
		} else if (userAgent.contains("Opera")) {
			browser = Browser.Opera;
		} else if (os == OS.Windows && userAgent.contains("MSIE 5.0")) {
			browser = Browser.IE;
		} else if (os == OS.Windows && userAgent.contains("MSIE 5.5")) {
			browser = Browser.IE;
			browserVersion = 55;
		} else if (os == OS.Windows && 
				(userAgent.contains("MSIE 6") ||
				 userAgent.contains("MSIE 7") ||
				 userAgent.contains("MSIE 8"))) {
			browser = Browser.IE;
			browserVersion = 60;
		}
		
		String platformOverrideStr = request.getParameter("platform");
		String browserOverrideStr = request.getParameter("browser");
		String distributionOverrideStr = request.getParameter("distribution");
		osRequested = null;
		browserRequested = null;
		distributionRequested = null;
		
		if (platformOverrideStr != null) {
			platformOverrideStr = platformOverrideStr.toLowerCase();
			for (OS o : OS.values()) {
				if (o.name().toLowerCase().equals(platformOverrideStr)) {
					osRequested = o;
					break;
				}
			}
		}

		if (browserOverrideStr != null) {
			browserOverrideStr = browserOverrideStr.toLowerCase();
			for (Browser b : Browser.values()) {
				if (b.name().toLowerCase().equals(browserOverrideStr)) {
					browserRequested = b;
					break;
				}
			}
			/* allow special browser=safari parameter */
			if (browserRequested == null && browserOverrideStr.equals("safari")) {
				osRequested = OS.Mac;
				browserRequested = Browser.Khtml;
			}
		}
		
		if (distributionOverrideStr != null) {
			distributionOverrideStr = distributionOverrideStr.toLowerCase();
			for (Distribution d : Distribution.values()) {
				if (d.name().toLowerCase().equals(distributionOverrideStr)) {
					distributionRequested = d;
					// implies platform=linux
					if (osRequested == null)
						osRequested = OS.Linux;
					break;
				}
			}
		}
		
		logger.debug("User agent is '{}' analysis {}", userAgent, this);
	}
	
	public static BrowserBean getForRequest(HttpServletRequest request) {
		BrowserBean bean = (BrowserBean)request.getAttribute("browser");
		if (bean == null) {
			bean = new BrowserBean(request);
			request.setAttribute("browser", bean);
		}
		
		return bean;
	}

	/* 
	 * The "isFooRequested" flavors indicate whether the user explicitly 
	 * chose the given platform/browser, e.g. on /bookmark where you can
	 * look at other browser versions even if you're using a different browser.
	 * 
	 * The plain "isFoo" indicate what user agent someone is using, 
	 * which should be used if you're trying to choose which html/css to 
	 * display or something like that. 
	 */
	
	private boolean isRequested(Browser b) {
		return browserRequested == b || (browserRequested == null && browser == b);
	}
	
	private boolean isRequested(OS o) {
		return osRequested == o || (osRequested == null && os == o);
	}
	
	private boolean isRequested(Distribution d) {
		return distributionRequested == d || (distributionRequested == null && distribution == d);
	}
	
	public boolean isGecko() {
		return browser == Browser.Gecko;
	}

	public boolean isGeckoRequested() {
		return isRequested(Browser.Gecko);
	}
	
	public boolean isGeckoAtLeast10() {
		return isGecko() && browserVersion >= 10;
	}

	public boolean isGeckoAtLeast15() {
		return isGecko() && browserVersion >= 15;
	}

	public boolean isIe() {
		return browser == Browser.IE;
	}

	public boolean isIeRequested() {
		return isRequested(Browser.IE);
	}
	
	public boolean isIeAtLeast55() {
		return isIe() && browserVersion >= 55;
	}

	public boolean isIeAtLeast60() {
		return isIe() && browserVersion >= 60;
	}

	public boolean isKhtml() {
		return browser == Browser.Khtml;
	}

	public boolean isKhtmlRequested() {
		return isRequested(Browser.Khtml);
	}
	
	public boolean isLinux() {
		return os == OS.Linux;
	}

	public boolean isLinuxRequested() {
		return isRequested(OS.Linux);
	}
	
	public boolean isMac() {
		return os == OS.Mac;
	}

	public boolean isMacRequested() {
		return isRequested(OS.Mac);
	}
	
	public boolean isOpera() {
		return browser == Browser.Opera;
	}

	public boolean isOperaRequested() {
		return isRequested(Browser.Opera);
	}
	
	public boolean isWindows() {
		return os == OS.Windows;
	}
	
	public boolean isWindowsRequested() {
		return isRequested(OS.Windows);
	}

	public boolean isSafari() {
		return isMac() && isKhtml();
	}

	public boolean isSafariRequested() {
		return isMacRequested() && isKhtmlRequested();
	}
	
	public boolean isFedora5() {
		return distribution == Distribution.Fedora5;
	}
	
	public boolean isFedora6() {
		return distribution == Distribution.Fedora6;
	}
	
	public boolean isFedora5Requested() {
		return isRequested(Distribution.Fedora5);
	}
	
	public boolean isFedora6Requested() {
		return isRequested(Distribution.Fedora6);
	}
	
	public String getSupportedBrowsers() {
		return "Internet Explorer 6 and Firefox 1.5";
	}
	
	public boolean isSupported() {
		return isIeAtLeast60() || isGeckoAtLeast15();
	}
	
	public boolean getIeAlphaImage() {
		return isIeAtLeast55() && browserVersion < 70;
	}
	
	@Override
	public String toString() {
		return "{os=" + os + " browser=" + browser + " version=" + browserVersion + " osRequested=" + osRequested + " browserRequested=" + browserRequested + " distribution=" + distribution + " distributionRequested=" + distributionRequested + "}";
	}
}

dumbhippo/branches/production-replaced-2006-12-13/server/src/com/dumbhippo/web/SigninBean.java
package com.dumbhippo.web;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;
import com.dumbhippo.identity20.Guid;
import com.dumbhippo.persistence.Account;
import com.dumbhippo.persistence.Client;
import com.dumbhippo.persistence.User;
import com.dumbhippo.server.AccountSystem;
import com.dumbhippo.server.Configuration;
import com.dumbhippo.server.HippoProperty;
import com.dumbhippo.server.NotFoundException;
import com.dumbhippo.server.views.Viewpoint;
import com.dumbhippo.web.CookieAuthentication.NotLoggedInException;
import com.dumbhippo.web.LoginCookie.BadTastingException;

/**
 * An object that caches the currently logged in user, stored in JSF
 * and the HTTP session.
 * 
 * @author walters
 *
 */
public abstract class SigninBean  {
	private static final Logger logger = GlobalSetup.getLogger(SigninBean.class);
	
	private static final String USER_ID_KEY = "dumbhippo.signedInUserId";
	private static final String CLIENT_ID_KEY = "dumbhippo.signedInClient";
	private static final String SIGNIN_BEAN_KEY = "signin";
	
	private String server;
	
	public static SigninBean getForRequest(HttpServletRequest request) {
		SigninBean result = null;
		
		if (request == null)
			throw new NullPointerException("null request");
		
		try {
			result = (SigninBean) request.getAttribute(SIGNIN_BEAN_KEY);
		} catch (ClassCastException e) {
			logger.error("Value of {} wasn't a SigninBean", SIGNIN_BEAN_KEY);
			result = null;
		}
		
		if (result == null) {
			Guid userGuid = null;
			Account account = null;
			
			// We can't cache the User or Account objects in session scope since we won't notice if 
			// there are changes to them. So we cache SigninBean only with request scope and put 
			// only the guid in session scope. This also nicely dodges threading issues since 
			// Guid is immutable.
			userGuid = (Guid) request.getSession().getAttribute(USER_ID_KEY);
					
			if (userGuid == null) {
				try {
					account = CookieAuthentication.authenticate(request);
					userGuid = account.getOwner().getGuid();
					storeGuid(request.getSession(), userGuid);
					logger.debug("storing authenticated user {} in session", account.getOwner());
				} catch (BadTastingException e) {
					logger.warn("Cookie was malformed", e);
					userGuid = null;
				} catch (NotLoggedInException e) {
					logger.debug("Cookie not valid: {}", e.getMessage());
					userGuid = null;
				}
			} else {
				AccountSystem accountSystem = WebEJBUtil.defaultLookup(AccountSystem.class);
				try {
					account = accountSystem.lookupAccountByOwnerId(userGuid);
				} catch (NotFoundException e) {
					logger.warn("Couldn't load account for stored authenticated user");
				}
			}
			
			if (account != null) {
				if (!account.getHasAcceptedTerms() || account.isDisabled() || account.isAdminDisabled())
					result = new DisabledSigninBean(account);
				else
					result = new UserSigninBean(account);
			} else
				result = new AnonymousSigninBean();

			logger.debug("storing SigninBean on request, valid = {}", result.isValid());
			request.setAttribute(SIGNIN_BEAN_KEY, result);
			
		}
				
		return result;
	}
	
	public static String computeClientIdentifier(HttpServletRequest request) {
		StringBuilder ret = new StringBuilder();
		ret.append(request.getRemoteAddr());
		String agent = request.getHeader("user-agent");
		if (agent != null) {
			ret.append('/');
			ret.append(agent);
		}
		
		return ret.toString();
	}
	
	public static void storeGuid(HttpSession session, Guid guid) {
		session.setAttribute(USER_ID_KEY, guid);		
	}

	/**
	 * Store authentication information on the session and/or in a persistant client
	 * cookie after initial authentication of a client
	 * 
	 * @param request request object
	 * @param response response object
	 * @param client Client object that the user has authenticated against
	 * @return a string that indicates a good default location for the state of the user;
	 *    for example, if the account is disabled, we return "/we-miss-you" where the
	 *    user is allowed to re-enable their account
	 */
	public static String initializeAuthentication(HttpServletRequest request, HttpServletResponse response, Client client) {
		Account account = client.getAccount();
		User user = account.getOwner();
		if (!account.isDisabled() && !account.isAdminDisabled() && account.getHasAcceptedTerms()) {
			setCookie(response, user.getGuid(), client.getAuthKey());
		} else {
			SigninBean.storeGuid(request.getSession(), user.getGuid());
			request.getSession().setAttribute(CLIENT_ID_KEY, client.getId());		
		}		

		if (account.isDisabled())
			return "/we-miss-you";
		else if (!account.getHasAcceptedTerms())
			return "/download?acceptMessage=true";
		else
			return "/";
	}
	
	/**
	 * Update stored authentication information on the session and/or in client cookies
	 * after a possible change in the enablement of an account
	 * @param request request object
	 * @param response response object
	 */
	public static void updateAuthentication(HttpServletRequest request, HttpServletResponse response) {
		AccountSystem accountSystem = WebEJBUtil.defaultLookup(AccountSystem.class);
		Guid userId = (Guid)request.getSession().getAttribute(USER_ID_KEY);
		Long clientId = (Long)request.getSession().getAttribute(CLIENT_ID_KEY);
		if (userId != null && clientId != null) {
			try {
				Client client = accountSystem.getExistingClient(userId, clientId);
				Account account = client.getAccount();
				if (!account.isDisabled() && !account.isAdminDisabled() && account.getHasAcceptedTerms())
					setCookie(response, userId, client.getAuthKey());
				else
					unsetCookie(response);
			} catch (NotFoundException e) {
				// Client must have been deleted since we first authorized the session, do nothing
			}
		}
	}
	
	private static void setCookie(HttpServletResponse response, Guid personId, String authKey) {
		Configuration config = WebEJBUtil.defaultLookup(Configuration.class);
		String host = config.getBaseUrl().getHost();
		
		LoginCookie loginCookie = new LoginCookie(host, personId.toString(), authKey);
		response.addCookie(loginCookie.getCookie());
		logger.debug("Set cookie for personId = {} authKey = {}", personId, authKey);
	}

	public static void unsetCookie(HttpServletResponse response) {
		response.addCookie(LoginCookie.newDeleteCookie());
		logger.debug("Unset auth cookie");
	}
	
	/** 
	 * Return the server in host:port format suitable for use in a URI,
	 * used for example to generate mugshot: URIs or absolute links.
	 * 
	 * Sets a precedent for random global configuration available from 
	 * SigninBean, for better or worse. Add a "config" bean? This 
	 * is a simple approach for now, we'll see if it gets out of hand.
	 * 
	 * @return the server name
	 */
	public String getServer() {
		if (server == null) {
			Configuration config = WebEJBUtil.defaultLookup(Configuration.class);
			String url = config.getPropertyFatalIfUnset(HippoProperty.BASEURL);
			// if you get this exception, should probably just add new 
			// config props for host and port
			if (!url.startsWith("http://") || url.endsWith("/"))
				throw new RuntimeException("FIXME need to be smarter");
			server = url.substring("http://".length());
		}
		return server;
	}
	
	public abstract boolean isValid();
	public abstract boolean isDisabled();
	public abstract boolean getNeedsTermsOfUse();
	
	public abstract Viewpoint getViewpoint();
	
	/**
	 * Clear any cached objects that might be associated with a particular
	 * Hibernate session and transaction. We use this in RewriteServlet 
	 * to avoid having the User object in the SigninBean be detached from the 
	 * the transaction we create when handling a JSP page. This is a bit
	 * hacky ... with some reorganization it should be possible to
	 * scope the transaction around the lookup of the User as well ...
	 * but it keeps things simple. 
	 */	
	public abstract void resetSessionObjects();
}

dumbhippo/branches/production-replaced-2006-12-13/server/web/jsp3/active-groups.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<dh:bean id="activeGroups" class="com.dumbhippo.web.pages.ActiveGroupsPage" scope="request"/>

<head>
	<title><c:out value="Active Groups - Mugshot"/></title>
	<dht3:stylesheet name="site" iefixes="true" lffixes="true"/>	
	<dht3:stylesheet name="person"/>
	<dht:faviconIncludes/>
</head>

<dht3:page>
	<dht3:pageSubHeader title="Active Groups">
	</dht3:pageSubHeader>
	
	<c:forEach items="${activeGroups.activeGroups.results}" var="group" varStatus="stackStatus">
	    <dht3:groupStack who="${group.groupView}" stackOrder="${stackStatus.count}" blocks="${group.blocks}" showFrom="true"/>
	</c:forEach>
    <dht:expandablePager pageable="${activeGroups.activeGroups}"/>
</dht3:page>
</html>

dumbhippo/branches/production-replaced-2006-12-13/server/web/jsp3/active-people.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<dh:bean id="activePeople" class="com.dumbhippo.web.pages.ActivePeoplePage" scope="request"/>

<head>
	<title><c:out value="Active People - Mugshot"/></title>
	<dht3:stylesheet name="site" iefixes="true" lffixes="true"/>	
	<dht3:stylesheet name="person"/>
	<dht:faviconIncludes/>
</head>

<dht3:page>
	<dht3:pageSubHeader title="Active People">
	</dht3:pageSubHeader>
	
	<c:forEach items="${activePeople.activePeople.results}" var="person" varStatus="stackStatus">
		<dht3:personStack person="${person.personView}" stackOrder="${stackStatus.count + 1}" stackType="dhMugshot" blocks="${person.blocks}" showFrom="true"/>
	</c:forEach>
    <dht:expandablePager pageable="${activePeople.activePeople}"/>
</dht3:page>
</html>

dumbhippo/branches/production-replaced-2006-12-13/server/web/jsp3/bookmark.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<jsp:forward page="/links-learnmore"/>

dumbhippo/branches/production-replaced-2006-12-13/server/web/jsp3/download.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<dh:bean id="welcome" class="com.dumbhippo.web.pages.DownloadPage" scope="page"/>
<jsp:setProperty name="welcome" property="invitationId" param="invite"/>
<jsp:setProperty name="welcome" property="inviterId" param="inviter"/>

<c:set var="urlParams" value=''/>
<c:set var="acceptMessage" value='false'/>
<c:if test='${!empty param["acceptMessage"]}'>
    <c:set var="acceptMessage" value='${param["acceptMessage"]}'/>
    <c:set var="urlParams" value='&acceptMessage=${param["acceptMessage"]}'/>    
</c:if>
<c:if test='${!empty param["invite"]}'>
    <c:set var="urlParams" value='${urlParams}&invite=${param["invite"]}'/>    
</c:if>
<c:if test='${!empty param["inviter"]}'>
    <c:set var="urlParams" value='${urlParams}&inviter=${param["inviter"]}'/>    
</c:if>

<head>
	<title>Mugshot Download</title>
	<dht3:stylesheet name="site" iefixes="true" lffixes="true"/>	
	<dht3:stylesheet name="download"/>
		<dh:script module="dh.download"/>
	<dht:faviconIncludes/>
	<script type="text/javascript">
		dh.download.needTermsOfUse = ${signin.needsTermsOfUse}
		dojo.event.connect(dojo, "loaded", function () { dh.download.init() })
	</script>	
</head>

<dht3:page>
	<dht3:shinyBox color="grey">
		<div class="dh-download-header-area">
			<div class="dh-download-header">Get Mugshot</div>
			<c:if test="${welcome.haveDownload}">
				<div class="dh-download-subtitle">Take advantage of all of our fun features with the Mugshot download.  It's easy and free!</div>
			</c:if>
			<div class="dh-download-terms">
				<c:choose>
					<c:when test="${signin.needsTermsOfUse}">
			        	<div id="dhAcceptTermsBox">        
					        <input type="checkbox" id="dhAcceptTerms" onclick="dh.download.updateDownload();">
						                <label for="dhAcceptTerms">I accept the Mugshot</label> <a href="javascript:window.open('/terms', 'dhTermsOfUse', 'menubar=no,scrollbars=yes,width=600,height=600');void(0);">terms and conditions</a>. (Required to continue.)
					        </input>
						</div>
		            </c:when>    
		            <c:otherwise>
		            </c:otherwise>
		        </c:choose>
			</div>
			<c:choose>
				<c:when test="${welcome.haveDownload}">
					<div class="dh-download-buttons">
						<%-- the class changes to dh-download-product-disabled in the javascript when one is not active --%>
						<a id="dhDownloadProduct" class="dh-download-product" href="javascript:dh.download.doDownload('${welcome.downloadUrl}')"><img src="/images3/${buildStamp}/download_now_button.gif"/></a>
						<a id="dhSkipDownload" class="dh-download-product" href="javascript:dh.download.doDownload()"><img src="/images3/${buildStamp}/no_thanks_button.gif"/></a>
						<i>  (This download is for <c:out value="${welcome.downloadFor}"/>.)</i>
					</div>
					<div class="dh-download-yadayada">
						Or, get Mugshot for another platform instead:
							<c:if test="${!browser.fedora5Requested}">
								<a href="/download?distribution=fedora5${urlParams}">Fedora Core 5</a>
							</c:if>
							<c:if test="${!browser.fedora6Requested}">
								<c:if test="${!browser.fedora5Requested}">| </c:if>
								<a href="/download?distribution=fedora6${urlParams}">Fedora Core 6</a>
							</c:if>
							<c:if test="${!browser.windowsRequested}">
								| <a href="/download?platform=windows${urlParams}">Windows XP</a>
							</c:if>
					</div>
				</c:when>
				<c:otherwise>
					<div class="dh-download-yadayada">
						We don't have Mugshot for your computer yet. (You can 
						download for <a href="/download?platform=windows${urlParams}">Windows XP</a> or 
						<a href="/download?distribution=fedora5${urlParams}">Fedora Core 5</a>.)
						<c:if test="${browser.macRequested}">We're still working on Mac OS X support.</c:if>
						You can use Mugshot without the download, however.
					</div>
					<div class="dh-download-yadayada">
						<a id="dhSkipDownload" class="dh-download-product" href="javascript:dh.download.doDownload()">Continue without downloading.</a>
					</div>
					<c:if test="${browser.linuxRequested}">
						<div class="dh-download-yadayada">						
							Contributed third-party builds <a href="http://developer.mugshot.org/wiki/Downloads">can be found on the Mugshot Wiki</a>.
							<c:if test="${signin.needsTermsOfUse}">Please also click "Continue without downloading"
							above to accept the terms of use, or Mugshot won't work.</c:if>
						</div>
					</c:if>
				</c:otherwise>
			</c:choose>
			<c:choose>
				<c:when test="${browser.linuxRequested}">
					<div class="dh-download-yadayada">
						<i>Source code is available in <a href="${welcome.downloadUrlLinuxTar}">tar.gz</a> and
						<a href="${welcome.downloadUrlSrpm}">SRPM</a> formats.</i>
					</div>
				</c:when>
			</c:choose>			
			<div class="dh-download-subheader">Here's what you can do with the Mugshot download...</div>
		</div>
		<dht3:webSwarmLearnMore>
			<a class="dh-download-learnmore dh-underlined-link" href="/links-learnmore">Learn more</a>		
		</dht3:webSwarmLearnMore>
		<dht3:radarLearnMore>
			<a class="dh-download-learnmore dh-underlined-link" href="/radar-learnmore">Learn more</a>	
		</dht3:radarLearnMore>
		<dht3:stackerLearnMore>
			<a class="dh-download-learnmore dh-underlined-link" href="/stacker-learnmore">Learn more</a>
		</dht3:stackerLearnMore>
		<div class="dh-download-faqs-header">Mugshot Download FAQs</div>
		<div class="dh-download-faq">
			<div class="dh-download-faq-q">Why do I need to download anything to use Mugshot?</div>
			<div class="dh-download-faq-a">The Mugshot download isn't required, but is recommended.  Your Mugshot page will work without it, but with it you'll have a
			more robust experience.</div>
		</div>
		<div class="dh-download-faq">
			<div class="dh-download-faq-q">How do I know Mugshot is running on my PC?</div>
			<div class="dh-download-faq-a">
			<c:choose>
				<c:when test="${browser.windows}">
					<div>Look in your Windows system tray for the Mugshot icon - it will look something like this:</div>
					<dht3:toolTrayPointer/>
				</c:when>
				<c:when test="${browser.linux}">
					<div>Look in your panel for the Mugshot icon - it will look something like this:</div>				
					<dht3:toolTrayPointer/>						
				</c:when>
				<c:otherwise>
					No instructions available right now for your computer operating system - check back later!
				</c:otherwise>
			</c:choose>
			</div>
		</div>
		<div class="dh-download-faq">
			<div class="dh-download-faq-q">Do I need a Mugshot account to use it?</div>
			<div class="dh-download-faq-a">Without an account, the Mugshot download doesn't do anything useful except sit in your system tray and look pretty.  <a href="/signup">Sign up!</a></div>
		</div>
		<div class="dh-download-faq">
			<div class="dh-download-faq-q">Is there a Mugshot download for Mac?</div>
			<div class="dh-download-faq-a">Not right now, but it's on our "to do" list.  If you're a developer, you can <a href="http://developer.mugshot.org/">help develop</a> it!</div>
		</div>						
	</dht3:shinyBox>
</dht3:page>

dumbhippo/branches/production-replaced-2006-12-13/server/web/jsp3/history.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>

<dht3:personPage pageName="History" stackSize="15"/>