dumbhippo/branches/jboss-upgrade/server/src/com/dumbhippo/statistics/StatisticsServiceMBean.java
package com.dumbhippo.statistics;

import org.jboss.system.ServiceMBean;

// To be a valid MBean, StatisticsService needs to implement
// a service with this name; but we don't actually need
// anything beyond what's in the base ServiceMBean interface.
public interface StatisticsServiceMBean extends ServiceMBean {
}

dumbhippo/branches/jboss-upgrade/server/src/com/dumbhippo/web/BrowserBean.java
package com.dumbhippo.web;

import java.io.Serializable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;

public class BrowserBean implements Serializable {
	private static final long serialVersionUID = 1L;
	@SuppressWarnings("unused")
	private static final Logger logger = GlobalSetup.getLogger(BrowserBean.class);

	private enum OS { Mac, Windows, Linux, Unknown };
	private enum Browser { Khtml, Gecko, Opera, IE, Unknown };
	
	private OS os;
	private Browser browser;
	private int browserVersion;
	
	private OS osRequested;
	private Browser browserRequested;
	
	private BrowserBean(HttpServletRequest request) {
		
		os = OS.Unknown;
		browser = Browser.Unknown;
		browserVersion = 0;
				
		String userAgent = request.getHeader("User-Agent");
		if (userAgent == null) {
			logger.debug("No User-Agent");
			return;
		}
		
		if (userAgent.contains("X11"))
			os = OS.Linux;
		else if (userAgent.contains("Macintosh"))
			os = OS.Mac;
		else if (userAgent.contains("Windows"))
			os = OS.Windows;

		/* note that we aren't counting IE before 5.0 or not on Windows 
		 * as IE ... it's just Unknown.
		 * For Netscape 4 and old Mozilla I'm guessing we should do
		 * the same but would require some research into
		 * gecko/netscape user agent history to see which changes make
		 * sense. 
		 */
		
		if (userAgent.contains("Konqueror") ||
		    userAgent.contains("Safari"))
		    browser = Browser.Khtml;
		else if (userAgent.contains("Gecko")) {
			browser = Browser.Gecko;
			Pattern p = Pattern.compile("Gecko\\/([0-9]+)");
			Matcher m = p.matcher(userAgent);
			if (m.find()) {
				try {
					int geckoVersion = Integer.parseInt(m.group(1));
					if (geckoVersion > 20051001)
						browserVersion = 15;
					else if (geckoVersion > 20041101)
						browserVersion = 10;
				} catch (NumberFormatException e) {
				}
			}
		} else if (userAgent.contains("Opera")) {
			browser = Browser.Opera;
		} else if (os == OS.Windows && userAgent.contains("MSIE 5.0")) {
			browser = Browser.IE;
		} else if (os == OS.Windows && userAgent.contains("MSIE 5.5")) {
			browser = Browser.IE;
			browserVersion = 55;
		} else if (os == OS.Windows && 
				(userAgent.contains("MSIE 6") ||
				 userAgent.contains("MSIE 7") ||
				 userAgent.contains("MSIE 8"))) {
			browser = Browser.IE;
			browserVersion = 60;
		}
		
		String platformOverrideStr = request.getParameter("platform");
		String browserOverrideStr = request.getParameter("browser");
		osRequested = null;
		browserRequested = null;
		
		if (platformOverrideStr != null) {
			platformOverrideStr = platformOverrideStr.toLowerCase();
			for (OS o : OS.values()) {
				if (o.name().toLowerCase().equals(platformOverrideStr)) {
					osRequested = o;
					break;
				}
			}
		}

		if (browserOverrideStr != null) {
			browserOverrideStr = browserOverrideStr.toLowerCase();
			for (Browser b : Browser.values()) {
				if (b.name().toLowerCase().equals(browserOverrideStr)) {
					browserRequested = b;
					break;
				}
			}
			/* allow special browser=safari parameter */
			if (browserRequested == null && browserOverrideStr.equals("safari")) {
				osRequested = OS.Mac;
				browserRequested = Browser.Khtml;
			}
		}
		
		logger.debug("User agent is '{}' analysis {}", userAgent, this);
	}
	
	public static BrowserBean getForRequest(HttpServletRequest request) {
		BrowserBean bean = (BrowserBean)request.getAttribute("browser");
		if (bean == null) {
			bean = new BrowserBean(request);
			request.setAttribute("browser", bean);
		}
		
		return bean;
	}

	/* 
	 * The "isFooRequested" flavors indicate whether the user explicitly 
	 * chose the given platform/browser, e.g. on /bookmark where you can
	 * look at other browser versions even if you're using a different browser.
	 * 
	 * The plain "isFoo" indicate what user agent someone is using, 
	 * which should be used if you're trying to choose which html/css to 
	 * display or something like that. 
	 */
	
	private boolean isRequested(Browser b) {
		return browserRequested == b || (browserRequested == null && browser == b);
	}
	
	private boolean isRequested(OS o) {
		return osRequested == o || (osRequested == null && os == o);
	}
	
	public boolean isGecko() {
		return browser == Browser.Gecko;
	}

	public boolean isGeckoRequested() {
		return isRequested(Browser.Gecko);
	}
	
	public boolean isGeckoAtLeast10() {
		return isGecko() && browserVersion >= 10;
	}

	public boolean isGeckoAtLeast15() {
		return isGecko() && browserVersion >= 15;
	}

	public boolean isIe() {
		return browser == Browser.IE;
	}

	public boolean isIeRequested() {
		return isRequested(Browser.IE);
	}
	
	public boolean isIeAtLeast55() {
		return isIe() && browserVersion >= 55;
	}

	public boolean isIeAtLeast60() {
		return isIe() && browserVersion >= 60;
	}

	public boolean isKhtml() {
		return browser == Browser.Khtml;
	}

	public boolean isKhtmlRequested() {
		return isRequested(Browser.Khtml);
	}
	
	public boolean isLinux() {
		return os == OS.Linux;
	}

	public boolean isLinuxRequested() {
		return isRequested(OS.Linux);
	}
	
	public boolean isMac() {
		return os == OS.Mac;
	}

	public boolean isMacRequested() {
		return isRequested(OS.Mac);
	}
	
	public boolean isOpera() {
		return browser == Browser.Opera;
	}

	public boolean isOperaRequested() {
		return isRequested(Browser.Opera);
	}
	
	public boolean isWindows() {
		return os == OS.Windows;
	}
	
	public boolean isWindowsRequested() {
		return isRequested(OS.Windows);
	}

	public boolean isSafari() {
		return isMac() && isKhtml();
	}

	public boolean isSafariRequested() {
		return isMacRequested() && isKhtmlRequested();
	}
	
	public String getSupportedBrowsers() {
		return "Internet Explorer 6 and Firefox 1.5";
	}
	
	public boolean isSupported() {
		return isIeAtLeast60() || isGeckoAtLeast15();
	}
	
	public boolean getIeAlphaImage() {
		return isIeAtLeast55() && browserVersion < 70;
	}
	
	@Override
	public String toString() {
		return "{os=" + os + " browser=" + browser + " version=" + browserVersion + " osRequested=" + osRequested + " browserRequested=" + browserRequested + "}";
	}
}

dumbhippo/branches/jboss-upgrade/server/src/com/dumbhippo/web/SigninBean.java
package com.dumbhippo.web;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;

import com.dumbhippo.GlobalSetup;
import com.dumbhippo.identity20.Guid;
import com.dumbhippo.persistence.Account;
import com.dumbhippo.persistence.Client;
import com.dumbhippo.persistence.User;
import com.dumbhippo.server.AccountSystem;
import com.dumbhippo.server.Configuration;
import com.dumbhippo.server.HippoProperty;
import com.dumbhippo.server.NotFoundException;
import com.dumbhippo.server.Viewpoint;
import com.dumbhippo.web.CookieAuthentication.NotLoggedInException;
import com.dumbhippo.web.LoginCookie.BadTastingException;

/**
 * An object that caches the currently logged in user, stored in JSF
 * and the HTTP session.
 * 
 * @author walters
 *
 */
public abstract class SigninBean  {
	private static final Logger logger = GlobalSetup.getLogger(SigninBean.class);
	
	private static final String USER_ID_KEY = "dumbhippo.signedInUserId";
	private static final String CLIENT_ID_KEY = "dumbhippo.signedInClient";
	private static final String SIGNIN_BEAN_KEY = "signin";
	
	private String server;
	
	public static SigninBean getForRequest(HttpServletRequest request) {
		SigninBean result = null;
		
		if (request == null)
			throw new NullPointerException("null request");
		
		try {
			result = (SigninBean) request.getAttribute(SIGNIN_BEAN_KEY);
		} catch (ClassCastException e) {
			logger.error("Value of {} wasn't a SigninBean", SIGNIN_BEAN_KEY);
			result = null;
		}
		
		if (result == null) {
			Guid userGuid = null;
			Account account = null;
			
			// We can't cache the User or Account objects in session scope since we won't notice if 
			// there are changes to them. So we cache SigninBean only with request scope and put 
			// only the guid in session scope. This also nicely dodges threading issues since 
			// Guid is immutable.
			userGuid = (Guid) request.getSession().getAttribute(USER_ID_KEY);
					
			if (userGuid == null) {
				try {
					account = CookieAuthentication.authenticate(request);
					userGuid = account.getOwner().getGuid();
					storeGuid(request.getSession(), userGuid);
					logger.debug("storing authenticated user {} in session", account.getOwner());
				} catch (BadTastingException e) {
					logger.warn("Cookie was malformed", e);
					userGuid = null;
				} catch (NotLoggedInException e) {
					logger.debug("Cookie not valid: {}", e.getMessage());
					userGuid = null;
				}
			} else {
				AccountSystem accountSystem = WebEJBUtil.defaultLookup(AccountSystem.class);
				try {
					account = accountSystem.lookupAccountByOwnerId(userGuid);
				} catch (NotFoundException e) {
					logger.warn("Couldn't load account for stored authenticated user");
				}
			}
			
			if (account != null) {
				if (!account.getHasAcceptedTerms() || account.isDisabled() || account.isAdminDisabled())
					result = new DisabledSigninBean(account);
				else
					result = new UserSigninBean(account);
			} else
				result = new AnonymousSigninBean();

			logger.debug("storing SigninBean on request, valid = {}", result.isValid());
			request.setAttribute(SIGNIN_BEAN_KEY, result);
			
		}
				
		return result;
	}
	
	public static String computeClientIdentifier(HttpServletRequest request) {
		StringBuilder ret = new StringBuilder();
		ret.append(request.getRemoteAddr());
		String agent = request.getHeader("user-agent");
		if (agent != null) {
			ret.append('/');
			ret.append(agent);
		}
		
		return ret.toString();
	}
	
	public static void storeGuid(HttpSession session, Guid guid) {
		session.setAttribute(USER_ID_KEY, guid);		
	}

	/**
	 * Store authentication information on the session and/or in a persistant client
	 * cookie after initial authentication of a client
	 * 
	 * @param request request object
	 * @param response response object
	 * @param client Client object that the user has authenticated against
	 * @return a string that indicates a good default location for the state of the user;
	 *    for example, if the account is disabled, we return "/we-miss-you" where the
	 *    user is allowed to re-enable their account
	 */
	public static String initializeAuthentication(HttpServletRequest request, HttpServletResponse response, Client client) {
		Account account = client.getAccount();
		User user = account.getOwner();
		if (!account.isDisabled() && !account.isAdminDisabled() && account.getHasAcceptedTerms()) {
			setCookie(response, user.getGuid(), client.getAuthKey());
		} else {
			SigninBean.storeGuid(request.getSession(), user.getGuid());
			request.getSession().setAttribute(CLIENT_ID_KEY, client.getId());		
		}		

		if (account.isDisabled())
			return "/we-miss-you";
		else if (!account.getHasAcceptedTerms())
			return "/download?acceptMessage=true";
		else
			return "/";
	}
	
	/**
	 * Update stored authentication information on the session and/or in client cookies
	 * after a possible change in the enablement of an account
	 * @param request request object
	 * @param response response object
	 */
	public static void updateAuthentication(HttpServletRequest request, HttpServletResponse response) {
		AccountSystem accountSystem = WebEJBUtil.defaultLookup(AccountSystem.class);
		Guid userId = (Guid)request.getSession().getAttribute(USER_ID_KEY);
		Long clientId = (Long)request.getSession().getAttribute(CLIENT_ID_KEY);
		if (userId != null && clientId != null) {
			try {
				Client client = accountSystem.getExistingClient(userId, clientId);
				Account account = client.getAccount();
				if (!account.isDisabled() && !account.isAdminDisabled() && account.getHasAcceptedTerms())
					setCookie(response, userId, client.getAuthKey());
				else
					unsetCookie(response);
			} catch (NotFoundException e) {
				// Client must have been deleted since we first authorized the session, do nothing
			}
		}
	}
	
	private static void setCookie(HttpServletResponse response, Guid personId, String authKey) {
		Configuration config = WebEJBUtil.defaultLookup(Configuration.class);
		String host = config.getBaseUrl().getHost();
		
		LoginCookie loginCookie = new LoginCookie(host, personId.toString(), authKey);
		response.addCookie(loginCookie.getCookie());
		logger.debug("Set cookie for personId = {} authKey = {}", personId, authKey);
	}

	public static void unsetCookie(HttpServletResponse response) {
		response.addCookie(LoginCookie.newDeleteCookie());
		logger.debug("Unset auth cookie");
	}
	
	/** 
	 * Return the server in host:port format suitable for use in a URI,
	 * used for example to generate mugshot: URIs or absolute links.
	 * 
	 * Sets a precedent for random global configuration available from 
	 * SigninBean, for better or worse. Add a "config" bean? This 
	 * is a simple approach for now, we'll see if it gets out of hand.
	 * 
	 * @return the server name
	 */
	public String getServer() {
		if (server == null) {
			Configuration config = WebEJBUtil.defaultLookup(Configuration.class);
			String url = config.getPropertyFatalIfUnset(HippoProperty.BASEURL);
			// if you get this exception, should probably just add new 
			// config props for host and port
			if (!url.startsWith("http://") || url.endsWith("/"))
				throw new RuntimeException("FIXME need to be smarter");
			server = url.substring("http://".length());
		}
		return server;
	}
	
	public abstract boolean isValid();
	public abstract boolean isDisabled();
	public abstract boolean getNeedsTermsOfUse();
	
	public abstract Viewpoint getViewpoint();
	
	/**
	 * Clear any cached objects that might be associated with a particular
	 * Hibernate session and transaction. We use this in RewriteServlet 
	 * to avoid having the User object in the SigninBean be detached from the 
	 * the transaction we create when handling a JSP page. This is a bit
	 * hacky ... with some reorganization it should be possible to
	 * scope the transaction around the lookup of the User as well ...
	 * but it keeps things simple. 
	 */	
	public abstract void resetSessionObjects();
}

dumbhippo/branches/jboss-upgrade/server/web/jsp2/bookmark.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>

<dh:bean id="bookmark" class="com.dumbhippo.web.pages.BookmarkPage" scope="request"/>

<c:choose>
<%-- note that by "IE" browser bean means specifically "Windows IE" --%>
<c:when test='${browser.ieRequested}'>
	<c:set var="unsupported" value="false" scope="page"/>	
</c:when>
<c:when test='${browser.geckoRequested}'>
	<c:set var="dragDestImg" value="bookmarkfirefox.gif" scope="page"/>
	<c:set var="browserTitle" value="FIREFOX" scope="page"/>
	<c:set var="unsupported" value="false" scope="page"/>	
</c:when>
<c:when test='${browser.safariRequested}'>
	<c:set var="dragDestImg" value="bookmarksafari.gif" scope="page"/>
	<c:set var="browserTitle" value="SAFARI" scope="page"/>
	<c:set var="unsupported" value="false" scope="page"/>	
</c:when>
<c:otherwise>
	<c:set var="unsupported" value="true" scope="page"/>
</c:otherwise>
</c:choose>

<head>
	<title>Mugshot Bookmark</title>
	<link rel="stylesheet" type="text/css" href="/css2/${buildStamp}/bookmark.css"/>
	<dht:faviconIncludes/>
	<dht:scriptIncludes/>
</head>
<dht:systemPage topImage="/images2/${buildStamp}/header_bookmark500.gif" fullHeader="true">
<c:choose>
	<c:when test="${browser.ieRequested}">
		<dht:zoneBoxTitle>USING MUGSHOT WEB SWARM</dht:zoneBoxTitle>	
		Since you're using Internet Explorer, you can <a href="/download">download</a> the
		Web Swarm application and share links right from your Explorer toolbar. Just click
		on the button with the bee when you are on the page you want to share. Then enter 
		Mugshot groups, users, or friends' e-mails as recipients, offer a quick description,
		and send it out!
		<br/>
		<img src="/images2/${buildStamp}/toolbarsample.gif"/>
	</c:when>
	<c:when test="${unsupported}">
		<dht:zoneBoxTitle>BROWSER NOT SUPPORTED</dht:zoneBoxTitle>		
		Your browser isn't recognized as being supported.  We're working on supporting
		more, check back here later.  You can see instructions for different browsers
		below; one of them might apply for you.
	</c:when>
	<c:otherwise>
	<dht:zoneBoxTitle>USING MUGSHOT WEB SWARM IN <c:out value="${browserTitle}"/></dht:zoneBoxTitle>
	<p>Drag the link below onto the Bookmarks toolbar.  Then to share and chat about
	a site with friends, click 'Mugshot Web Swarm' on your Bookmarks toolbar.</p>
	<div id="dhBookmarkHowto">
	<table cellspacing="0" cellpadding="0">
	<tr>
	<td width="10px;"><div></div></td>
	<td align="left" valign="bottom"><img src="/images2/${buildStamp}/dragthis.gif"/></td>
	<td align="center" valign="bottom">
	<div id="dhBookmarkLink">
	<a href="javascript:window.open('${bookmark.baseUrl}/sharelink?v=1&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&next=close','_NEW','menubar=no,location=no,toolbar=no,scrollbars=yes,status=no,resizable=yes,height=400,width=550,top='+((screen.availHeight-400)/2)+',left='+((screen.availWidth-550)/2));void(0);">Mugshot Web Swarm</a>
	</div>
	</td>
	<td align="right" valign="bottom"><img src="/images2/${dragDestImg}"/></td>
	<td width="10px;"><div></div></td>	
	</tr>
	</table>
	</div>
	<dht:zoneBoxTitle>IF THE BOOKMARK DOESN'T SHOW UP IN THE TOOLBAR</dht:zoneBoxTitle>
	<p>Go to the <span class="dh-bookmark-uiref">View</span> menu, and under <span class="dh-bookmark-uiref">Toolbars</span> make sure <span class="dh-bookmark-uiref">Bookmark Toolbar</span> is
	checked.</p>
	<p>If you see the Bookmark Toolbar but 'Mugshot Web Swarm' does not appear on it,
	choose <span class="dh-bookmark-uiref">Manage Bookmarks</span> from the <span class="dh-bookmark-uiref">Bookmarks</span> menu,
	and move the bookmark to your <span class="dh-bookmark-uiref">Personal Toolbar</span> folder.
	</p>
	</c:otherwise>
</c:choose>	
	<dht:zoneBoxSeparator/>
	<div class="dh-option-list">
	Instructions for: <a class="dh-option-list-option" href="?browser=ie">Internet Explorer</a> | 
	<a class="dh-option-list-option" href="?browser=gecko">Firefox</a> | 
	<a class="dh-option-list-option" href="?browser=safari">Safari</a>
	</div>
</dht:systemPage>
</html>

dumbhippo/branches/jboss-upgrade/server/web/jsp2/busy.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>

<jsp:forward page="/error">
	<jsp:param name="text" value="More people are trying to use Mugshot than we can handle right now; try back later!"/>
</jsp:forward>

dumbhippo/branches/jboss-upgrade/server/web/jsp2/comingsoon.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>



<%-- Please don't bother hacking on this page much, it will only be used for another week or so --%>



<head>
	<title>Coming Soon!</title>
	<link rel="stylesheet" type="text/css" href="/css2/${buildStamp}/site.css"/>
	<dht:faviconIncludes/>	
	<dht:scriptIncludes/>
</head>
<dht:systemPage disableJumpTo="true" topImage="/images2/${buildStamp}/header_blank500.gif">
	<div>
		This site is currently <b>SECRET</b> and <b>EXCLUSIVE</b>.
	</div>
	<br/>
	<div>
		If you have an account already, <b><a href="/who-are-you">please log in</a></b>.
	</div>
	<br/>	
	<div>
		If you're curious, leave your email address here, and we'll let you know when we launch.
		<br/>
		<dht:wantsIn/>		
	</div>
</dht:systemPage>
</html>

dumbhippo/branches/jboss-upgrade/server/web/jsp2/home.jsp
<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>

<c:if test="${!signin.valid}">
	<%-- this is a bad error message but should never happen since we require signin to get here --%>
	<dht:errorPage>Not signed in</dht:errorPage>
</c:if>

<head>
	<title>Mugshot Home</title>
	<link rel="stylesheet" type="text/css" href="/css2/${buildStamp}/home.css"/>
	<dht:faviconIncludes/>
	<dht:scriptIncludes/>
</head>
<dht:twoColumnPage disableHomeLink="true">
	<dht:sidebarPerson who="${signin.user.id}">
		<c:if test="${browser.windows}">
			<dht:sidebarBoxControls title="WINDOWS CONTROLS">
				<dht:actionLink href="/download" title="Download and install Mugshot for Windows to use Web Swarm and Music Radar">Download for Windows</dht:actionLink>
			</dht:sidebarBoxControls>
		</c:if>
		<c:if test="${browser.linux}">
			<dht:sidebarBoxControls title="LINUX CONTROLS">
				<dht:actionLink href="/download" title="Download and install Mugshot for Linux to use Web Swarm and Music Radar">Download for Linux</dht:actionLink>
			</dht:sidebarBoxControls>
		</c:if>
		<c:if test="${browser.gecko}">
			<dht:sidebarBoxControls title="FIREFOX CONTROLS">
				<dht:actionLink href="/bookmark" title="Add the Link Share Link to your Mozilla Firefox Browser">Add Mugshot to Firefox</dht:actionLink>
			</dht:sidebarBoxControls>
		</c:if>
		<c:if test="${browser.khtml}">
			<dht:sidebarBoxControls title="SAFARI CONTROLS">
				<dht:actionLink href="/bookmark" title="Add the Link Share Link to your Safari Browser">Add Mugshot to Safari</dht:actionLink>
			</dht:sidebarBoxControls>
		</c:if>
	</dht:sidebarPerson>
	<dht:contentColumn>
		<dht:zoneBoxWeb more="true">
		    <dht:linkSwarmPromo browserInstructions="true" linksLink="true" separator="true"/>	
			<dht:requireLinksPersonBean who="${signin.user.id}"/>
			<c:if test="${links.favoritePosts.resultCount > 0}">
				<dht:zoneBoxTitle>FAVES</dht:zoneBoxTitle>
					<dht:postList posts="${links.favoritePosts.results}" format="simple"/>
				<dht:zoneBoxSeparator/>
			</c:if>
			<c:choose>
				<c:when test="${links.receivedPosts.totalCount > 0}">
				    <dht:zoneBoxTitle>SHARED WITH YOU</dht:zoneBoxTitle>
					<dht:postList posts="${links.receivedPosts.results}" format="simple"/>
				</c:when>
				<c:otherwise>
					<dht:requireLinksGlobalBean/>
					<dht:zoneBoxTitle>RECENTLY SHARED</dht:zoneBoxTitle>
					<c:choose>
						<c:when test="${linksGlobal.hotPosts.resultCount > 0}">
							<dht:postList posts="${linksGlobal.hotPosts.results}" format="simple"/>
						</c:when>
						<c:otherwise>
							Nobody anywhere has ever shared anything!
						</c:otherwise>
					</c:choose>
				</c:otherwise>
			</c:choose>
		</dht:zoneBoxWeb>
		<dht:zoneBoxMusic more="true">
			<dht:musicRadarPromo separator="true"/>
			<c:if test="${signin.musicSharingEnabled}">
				<dht:requireMusicPersonBean who="${signin.user.id}"/>
				<dht:zoneBoxTitle>YOUR CURRENT SONG</dht:zoneBoxTitle>
				<dh:nowPlaying userId="${signin.user.id}" hasLabel="false"/>
				<dht:zoneBoxSeparator/>
				<dht:trackList name="FRIENDS' RECENT SONGS" tracks="${musicPerson.friendsRecentTracks.results}" separator="true" oneLine="true" displaySinglePersonMusicPlay="true" />
			</c:if>

			<dht:turnOnRadar/>

			<dht:requireMusicGlobalBean/>
			<dht:trackList name="MOST PLAYED SONGS TODAY" tracks="${musicGlobal.mostPlayedToday.results}" oneLine="true" />
		</dht:zoneBoxMusic>
		<dht:zoneBoxTv more="true">
			<dht:zoneBoxTitle>COMING SOON</dht:zoneBoxTitle>
			<p>We're actively working on our TV Party section, check our <a href="http://blog.mugshot.org/">blog</a> and the <a href="/tv">TV Party</a> page for updates.  Take a look at some of these blog entries for more details.</p>
			<ul>
			  <li><a href="http://blog.mugshot.org/?p=124">TV Dinner... Date?</a></li>
			  <li><a href="http://blog.mugshot.org/?p=107">Researching TV</a></li>
			  <li><a href="http://blog.mugshot.org/?p=84">Stick your TV shows on the wall</a></li>
			</ul>
		</dht:zoneBoxTv>
	</dht:contentColumn>
</dht:twoColumnPage>
</html>

dumbhippo/branches/jboss-upgrade/server/web/jsp2/unknownlink.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht" %>

<jsp:forward page="/error">
	<jsp:param name="text" value="That page doesn't exist."/>
</jsp:forward>